### ISSUE TITLE
Multicursor Vscode Command broken in `v0.7.0`

### ISSUE THREAD

**Issue by Platzer** [VSCodeVim/Vim#1652]
**BUG REPORT**

**Environment**:

- **VSCode Version**:
Version 1.12.1
Commit f6868fce3eeb16663840eb82123369dec6077a9b
Date 2017-05-04T21:26:50.689Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
- **VsCodeVim Version**: 
0.7.0
- **OS**: 
Win7 x64

**What happened**:
1. Add multicursor with Vscode shortcut `Ctrl-Alt down`
2. Try to add cursor below from command palette
3. Add multicursor with Vscode Vim command `gb`, that worked but multicursor has some weird selection behavior.

**What did you expect to happen**: 
1. Multicursor should be added below
2. Multicursor should be added below
3. Selction should not jump when moving cursors

**How to reproduce it**:
![multicursor_bug](https://cloud.githubusercontent.com/assets/3358663/25737023/c5a8a87c-3175-11e7-9f18-525f382cf135.gif)

**Comment by Chillee** [comment]
Can you confirm how many of these were regressions introduced in 0.7.0?

**Comment by Chillee** [comment]
As far as I can tell, there are 2 bugs here.

1. ctrl-alt down doesn't add a new cursor. I can't reproduce this one, but @johnfn can.
2. With multiple cursors, when moving the cursor past the beginning of the selection, the cursor jumps to the end. This doesn't appear to be a new bug introduced by 0.7.0

The middle bug isn't because of us. If you try removing the vscodevim plugin, the second issue still occurs.

**Comment by xconverge** [comment]
Just tested, this is not a regression in these specific versions, the regression is due to changes in vscode.

I tested 0.6.18 on old vscode and new vscode and it works on old but not on new with the reported behavior above.

**Comment by jpoon** [comment]
Yes, our unit tests are also failing due to this. Not entirely sure what the root cause is but here's the stack trace:

```
    at t._tryExecuteCommand (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1079483)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1079183
TypeError: Cannot read property 'source' of undefined
    at t.run (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1451464)
    at t.runEditorCommand (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1286732)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1074742
    at t.invokeFunction (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1106082)
    at t.invokeWithinContext (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1340806)
    at t.runCommand (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1074634)
    at handler (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1074106)
    at t.invokeFunction (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1106082)
    at t._tryExecuteCommand (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1079483)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1079183
```

**Comment by jpoon** [comment]
@rebornix any idea what could be going on?

**Comment by Platzer** [comment]
@jpoon thanks for filing the bug! I'm kind of busy :sob:, and had no change to get back here sooner!

**Comment by Platzer** [comment]
Working with vscode `1.13.0`!
