### ISSUE TITLE
Tests failing on master on Windows 

### ISSUE THREAD

**Issue by philipmat** [VSCodeVim/Vim#1914]
I'm creating this issue to track these four tests failing on Windows 10 on `master`.
I'll try working on them one at a time.

```
 1) read Can read shell command output:

      AssertionError: Content does not match; Expected=hey. Actual=hey
      + expected - actual

      -hey
      +hey

      at Object.assertEqualLines (C:\dev\vscodevim\Vim\test\testUtils.ts:28:12)
      at Object.<anonymous> (C:\dev\vscodevim\Vim\test\cmd_line\read.test.ts:20:5)
      at Generator.next (<anonymous>)
      at fulfilled (C:\dev\vscodevim\Vim\out\test\cmd_line\read.test.js:4:58)

  2) Basic sort Sort whole file, dsc:

      AssertionError: Line count does not match.
      + expected - actual

      -4
      +3

      at Object.assertEqualLines (C:\dev\vscodevim\Vim\test\testUtils.ts:35:10)
      at Object.<anonymous> (C:\dev\vscodevim\Vim\test\cmd_line\sort.test.ts:47:5)
      at Generator.next (<anonymous>)
      at fulfilled (C:\dev\vscodevim\Vim\out\test\cmd_line\sort.test.js:4:58)

  3) Basic sort Sort range, dsc:

      AssertionError: Line count does not match.
      + expected - actual

      -5
      +4

      at Object.assertEqualLines (C:\dev\vscodevim\Vim\test\testUtils.ts:35:10)
      at Object.<anonymous> (C:\dev\vscodevim\Vim\test\cmd_line\sort.test.ts:87:5)
      at Generator.next (<anonymous>)
      at fulfilled (C:\dev\vscodevim\Vim\out\test\cmd_line\sort.test.js:4:58)


  4) Mode Normal / can search through multiple newlines:

      Cursor LINE position is wrong.
      + expected - actual

      -0
      +1

      at Suite.suite (C:\dev\vscodevim\Vim\test\mode\modeNormal.test.ts:1492:3)
```

- [x] 1) read Can read shell command output - 
  *NOTE*: with neovim enabled the second line is "hey " <- extra space.  
  Without neovim it doesn't get the first empty line
- [x] 2) Basic sort Sort whole file, dsc:
  *NOTE*: with neovim there's a fourth empty line
- [x] 3) Basic sort Sort range, dsc:
  *NOTE*: probably same as 2)
- [x] 4) Mode Normal / can search through multiple newlines:

**Comment by philipmat** [comment]
Fixed with PR #1939
