### ISSUE TITLE
`gulp prettier` does not work on Windows

### ISSUE THREAD

**Issue by philipmat** [VSCodeVim/Vim#1961]
**Environment**:

- **VSCode Version**: 1.14
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10

```
> gulp prettier
[00:26:35] Using gulpfile C:\dev\vscodevim\Vim\gulpfile.js
[00:26:35] Starting 'prettier'...
'grep' is not recognized as an internal or external command,
operable program or batch file.
[00:26:35] 'prettier' errored after 21 ms
[00:26:35] Error: Command `git diff --name-only HEAD | grep ".*.[t|j]s$" | xargs ./node_modules/prettier/bin/prettier.js --write --print-width 100 --single-quote --trailing-comma es5` failed with exit code 255
    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by Chillee** [comment]
I will confess to not thinking about windows at all when writing this script...

I think I'll try and figure out if it's possible to add a post commit hook of some kind...

**Comment by philipmat** [comment]
I'll try to make it work across both platforms.
