### ISSUE TITLE
"TypeError: Cannot read property 'isEqual' of undefined" while debugging an extension with vim enabled

### ISSUE THREAD

**Issue by jprobichaud** [VSCodeVim/Vim#2019]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**: 
- **VSCode Version**: 1.15.1
- **VsCodeVim Version**:  0.10.0
- **OS**:  Windows 10 x64

**What happened**:
I'm developing a vscode extension and while I'm debugging my extension with breakpoints enabled, I often get this exception in the VSCode instance that has my extension code (not in the Extension Environment Host one):

```
Exception has occurred: Error
TypeError: Cannot read property 'isEqual' of undefined
    at ModeHandler.<anonymous> (C:\Users\jerobich\.vscode\extensions\vscodevim.vim-0.10.0\out\src\mode\modeHandler.js:505:58)
    at Generator.next (<anonymous>)
    at C:\Users\jerobich\.vscode\extensions\vscodevim.vim-0.10.0\out\src\mode\modeHandler.js:7:71
    at __awaiter (C:\Users\jerobich\.vscode\extensions\vscodevim.vim-0.10.0\out\src\mode\modeHandler.js:3:12)
    at ModeHandler.handleSelectionChange (C:\Users\jerobich\.vscode\extensions\vscodevim.vim-0.10.0\out\src\mode\modeHandler.js:459:16)
    at Object.promise (C:\Users\jerobich\.vscode\extensions\vscodevim.vim-0.10.0\out\src\mode\modeHandler.js:414:37)
    at TaskQueue.<anonymous> (C:\Users\jerobich\.vscode\extensions\vscodevim.vim-0.10.0\out\src\taskQueue.js:27:32)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\jerobich\.vscode\extensions\vscodevim.vim-0.10.0\out\src\taskQueue.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)

```

**What did you expect to happen**: 
no exceptions :)

**How to reproduce it**:
- launch my extension project in debug mode with a breakpoint
- trigger few breakpoints
- press Continue after I'm done 
- boom!

**Comment by jpoon** [comment]
We are a couple more commits ahead and I haven't come across this so going to close for now. Please re-open if you still see this.
