### ISSUE TITLE
running vscode from tmux on macos breaks vim ? 

### ISSUE THREAD

**Issue by a-eid** [VSCodeVim/Vim#2071]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

When I launch `code` from tmux on macos it breaks a few key bindings like `dd` . 
keep in mind that when launching it from tmux on linux(ubuntu) it works perfectly fine. 

### To Reproduce : 

just launch code from tmux and try to delete a line `dd` .

**Comment by jpoon** [comment]
I use `tmux` on my macos all the time, and haven't ever seen this. Will need to get more info. What other keybindings break?

**Comment by xconverge** [comment]
https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard#mac-os-x-pasteboard-access-under-tmux-and-screen

Is this possibly related?

**Comment by njurgens** [comment]
I ran into possibly the same issue with `dd`, `yy`, and others not working, but for me it happens if I have `"vim.useSystemClipboard": true`, regardless of whether I launch from `tmux` or run `Visual Studio Code.app` directly.

**Comment by a-eid** [comment]
@njurgens yes that's the same issue I am having .

**Comment by draco** [comment]
I just ran into the same issue as well on Linux. With `"vim.useSystemClipboard": true,`, `dd`, `x`, etc. aren't working for me.

**Comment by from-nibly** [comment]
I am having this same issue. `ciw` also doesn't work. it seems to run into some sort of error whenever you do something that interacts with the clipboard. It looks like its failing and then stopping the command.

I run on ubuntu 16.04 in xfce/i3 and I can't turn on "vim.useSystemClipboard" because of this.

**Comment by from-nibly** [comment]
Update I found the error message.

Looks like the extension depends on xsel. This is not documented and the extension does not include it.

```
Error: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel
	at handler (/home/jordan/.vscode/extensions/vscodevim.vim-0.11.2/node_modules/clipboardy/lib/linux.js:7:9)
	at Object.copySync (/home/jordan/.vscode/extensions/vscodevim.vim-0.11.2/node_modules/clipboardy/lib/linux.js:33:5)
	at Object.exports.writeSync.input [as writeSync] (/home/jordan/.vscode/extensions/vscodevim.vim-0.11.2/node_modules/clipboardy/index.js:38:13)
	at Function.Copy (/home/jordan/.vscode/extensions/vscodevim.vim-0.11.2/out/src/util.js:29:20)
	at Function.putNormalRegister (/home/jordan/.vscode/extensions/vscodevim.vim-0.11.2/out/src/register/register.js:154:30)
	at Function.put (/home/jordan/.vscode/extensions/vscodevim.vim-0.11.2/out/src/register/register.js:62:26)
	at YankOperator.<anonymous> (/home/jordan/.vscode/extensions/vscodevim.vim-0.11.2/out/src/actions/operator.js:239:33)
	at Generator.next (<anonymous>)
	at /home/jordan/.vscode/extensions/vscodevim.vim-0.11.2/out/src/actions/operator.js:13:71
	at Promise (<anonymous>)
```
