### ISSUE TITLE
VimState.editor can be undefined; leads to runtime error "Cannot read property 'document' of undefined"

### ISSUE THREAD

**Issue by nicksnyder** [VSCodeVim/Vim#2184]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

```
shell.ts:474 Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at HistoryTracker.getAllText (vscodevim.vim-0.10.3/out/src/history/historyTracker.js:149:36)
    at HistoryTracker._initialize (vscodevim.vim-0.10.3/out/src/history/historyTracker.js:161:78)
    at new HistoryTracker (vscodevim.vim-0.10.3/out/src/history/historyTracker.js:139:14)
    at new ModeHandler (vscodevim.vim-0.10.3/out/src/mode/modeHandler.js:400:40)
    at vscodevim.vim-0.10.3/out/extension.js:44:42
    at Generator.next (<anonymous>)
    at __awaiter (/vscodevim.vim-0.10.3/out/extension.js:12:71)
    at Promise (<anonymous>)
    at __awaiter (/vscodevim.vim-0.10.3/out/extension.js:8:12)
    at getAndUpdateModeHandler (/vscodevim.vim-0.10.3/out/extension.js:39:12)
```

The cause appears to be that the type of VimState.editor is incorrect. It is typed as `vscode.TextEditor` but it should be `vscode.TextEditor | undefined`:

Fixing the type causes a bunch of compile errors. Each compile error is a code path that could break if there is no active text editor.

```diff
$ git diff
diff --git a/src/mode/modeHandler.ts b/src/mode/modeHandler.ts
index 42104ae..6905c55 100644
--- a/src/mode/modeHandler.ts
+++ b/src/mode/modeHandler.ts
@@ -84,7 +84,7 @@ export class VimState {
    */
   public identity: EditorIdentity;

-  public editor: vscode.TextEditor;
+  public editor: vscode.TextEditor | undefined;

   /**
    * For timing out remapped keys like jj to esc.
```

**Comment by yasintz** [comment]
+1

**Comment by taozhi8833998** [comment]
+1
