### ISSUE TITLE
failed: Cannot read property 'overrideCopy' of undefined after upgrade to 0.10.12

### ISSUE THREAD

**Issue by camper42** [VSCodeVim/Vim#2321]
BUG REPORT

**What happened**:
```
workbench.main.js:sourcemap:249 [Extension Host] Activating extension `vscodevim.vim` failed:  Cannot read property 'overrideCopy' of undefined
t.log @ workbench.main.js:sourcemap:249
[Extension Host] Here is the error stack:  TypeError: Cannot read property 'overrideCopy' of undefined
	at ConfigurationClass.reload (/Users/camper42/.vscode/extensions/vscodevim.vim-0.10.12/out/src/configuration/configuration.js:272:95)
	at new ConfigurationClass (/Users/camper42/.vscode/extensions/vscodevim.vim-0.10.12/out/src/configuration/configuration.js:202:14)
	at Object.<anonymous> (/Users/camper42/.vscode/extensions/vscodevim.vim-0.10.12/out/src/configuration/configuration.js:358:25)
	at Object.<anonymous> (/Users/camper42/.vscode/extensions/vscodevim.vim-0.10.12/out/src/configuration/configuration.js:360:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.J.X.t.getExtensionPathIndex.then.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:490:709)
```

**What did you expect to happen**:
no error

**How to reproduce it (as minimally and precisely as possible)**:
upgrade to 0.10.12 and reload vs code

**Environment**:
Mac

- Extension (VsCodeVim) version: 0.10.12
- VSCode version:  1.19.2 (1.19.2)
- OS version: 10.13.2

**Comment by erikras** [comment]
Great! I was trying to figure out where to find the stacktrace to report that `0.10.12` is broken, and you beat me to it. 👍

**Comment by camper42** [comment]
Menu Bar -> Help -> Toggle Developer Tools
@erikras

**Comment by Volem** [comment]
0.10.12 breaking on windows 10. Installing back 0.10.11 fixes back
https://code.visualstudio.com/docs/editor/extension-gallery

**Comment by jpoon** [comment]
Goddamn it. I knew that would change would bite me in the butt. On a plane right now, fix should be pretty easy.

**Comment by hristod** [comment]
can it be fixing by somehow rolling back VS Code version or something? I can't work right now...

**Comment by jpoon** [comment]
Yah. Our download and install the old releases through the GH releases page. Damnit, I shouldn't have rushed this release our before my flight. I'll be landing in 2 hours, and will fix it as soon as I land.

**Comment by erikras** [comment]
@jpoon We all do dumb stuff like that. Thanks for being so attentive. 👍

**Comment by razagill** [comment]
Was scratching my head for half an hour on this one haha. @jpoon take it easy, happens sometime :). 
Thanks for the great extension!

**Comment by erikras** [comment]
I tried moving my cursor around with the arrow keys like an animal, but I think it'd be less painful to switch IDEs for a couple hours. 😆

**Comment by atrocious** [comment]
https://github.com/VSCodeVim/Vim/pull/2320/files#diff-d45fc41533f6675601aca5a0c1943ae9R155

This should be it, right? Moved from another file where Configuration was imported but should be `this` after move? :)

**Comment by hristod** [comment]
@jpoon It's not a big deal, we can always roll back. Have a safe flight!

**Comment by jpoon** [comment]
Should be all good now.
