### ISSUE TITLE
TypeError related to statusBar.foreground on VS Code 1.22.0-insider

### ISSUE THREAD

**Issue by vuldin** [VSCodeVim/Vim#2432]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**What happened**:
Updated to VS Code 1.22.0-insider, then attempted to view/edit files with this vim plugin.

**What did you expect to happen**:
Be able to navigate and edit.

**How to reproduce it (as minimally and precisely as possible)**:
Use this plugin with VS Code version 1.22.0-insider (latest as of this morning). When navigating (hjkl) the following error appears on each keystroke:

```
Error: TypeError: Cannot delete read only property 'statusBar.foreground' of object
    at Object.deleteProperty (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:524:821)
    at StatusBarImpl.SetColor (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/statusBar.js:30:20)
    at ModeHandler._renderStatusBar (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:1065:39)
    at ModeHandler.<anonymous> (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:1048:18)
    at Generator.next (<anonymous>)
    at /Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:3:12)
    at ModeHandler.updateView (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:884:16)
    at ModeHandler.<anonymous> (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:202:28)
    at Generator.next (<anonymous>)
    at /Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:3:12)
    at ModeHandler.handleSelectionChange (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:97:16)
    at Object.taskQueue_1.taskQueue.enqueueTask [as promise] (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/mode/modeHandler.js:68:58)
    at TaskQueue.<anonymous> (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/taskQueue.js:32:32)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/taskQueue.js:4:58)
    at <anonymous> (at TaskQueue.<anonymous> (/Users/joshua/.vscode-insiders/extensions/vscodevim.vim-0.11.1/out/src/taskQueue.js:36:29))
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:398
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

**Environment**:
VS Code on mac.

- Extension (VsCodeVim) version: 0.11.1
- VSCode version: 1.22.0-insider
- OS version: mac high sierra 10.13.3 (17D102)

**Comment by vuldin** [comment]
Opened issue on VS Code repo: https://github.com/Microsoft/vscode/issues/45340

**Comment by bpasero** [comment]
No, I think this is a VIM extension issue?

**Comment by jpoon** [comment]
This is the piece of code causing the issue:

```
  public SetColor(background: string, foreground?: string) {
    const currentColorCustomizations = vscode.workspace
      .getConfiguration('workbench')
      .get('colorCustomizations');

    const colorCustomizations = Object.assign(currentColorCustomizations || {}, {
      'statusBar.background': `${background}`,
      'statusBar.noFolderBackground': `${background}`,
      'statusBar.debuggingBackground': `${background}`,
      'statusBar.foreground': `${foreground}`,
    });

    if (foreground === undefined) {
      delete colorCustomizations['statusBar.foreground'];
    }
```

How do we revert the `statusBar.foreground` to VSCode's default?

**Comment by bpasero** [comment]
@jpoon oh I see, this is about configuration, I was wrong this could be us. I will reopen the issue in VS Code.

**Comment by bpasero** [comment]
@jpoon I think we pushed a fix 👍
