### ISSUE TITLE
VSCodeVim broken with latest VS Code Version 1.22.1

### ISSUE THREAD

**Issue by mario-grgic** [VSCodeVim/Vim#2519]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: VS Code upgraded to 1.22.1 and VSCodeVim stopped working. Enabling and disabling the extensions, or uninstalling and installing does not make it work.

**What did you expect to happen**: Usually extension would continue to work after update.

**How to reproduce it (as minimally and precisely as possible)**: All I had to do is update VS Code to newest version.

**Environment**:

VSCodeVim does not show under "Show running extensions" even though it is installed.

- Extension (VsCodeVim) version: 0.11.3
- VSCode version: 1.22.1
- OS version: macOS 10.13.4

**Comment by mario-grgic** [comment]
The console.log shows the following:

```
[Extension Host] Activating extension `vscodevim.vim` failed:  Cannot find module 'untildify'
t.log @ console.ts:136
[Extension Host] Here is the error stack:  Error: Cannot find module 'untildify'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/src/cmd_line/commands/file.js:15:19)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/src/cmd_line/commands/file.js:115:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/src/actions/commands/actions.js:21:16)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/src/actions/commands/actions.js:3848:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/src/register/register.js:11:19)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/src/register/register.js:356:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/src/actions/operator.js:22:20)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/src/actions/operator.js:943:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/src/actions/include-all.js:4:1)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/src/actions/include-all.js:18:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/extension.js:16:1)
	at Object.<anonymous> (/Users/mariogrgic/.vscode/extensions/vscodevim.vim-0.11.3/out/extension.js:315:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:30:770)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:676:131
	at t._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:676:243)
	at t._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:675:161)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:673:282)
	at e._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:417:920)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:417:539
	at Array.map (native)
	at e._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:417:514)
	at e.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:416:14)
	at t.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:673:646)
	at t.handleEagerExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:695:734)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:694:950
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:69:572)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:160)
	at e.open (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:339)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:673:320
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:69:572)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:160)
	at c (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:654)
	at q.then.o.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:868)
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:69:572)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:160)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:103:286
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:133:661
	at LOOP (fs.js:1728:14)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickCallback (internal/process/next_tick.js:104:9)
extensionService.ts:848 Activating extension 'vscodevim.vim' failed: Cannot find module 'untildify'.
w._logMessageInConsole @ extensionService.ts:848
```

**Comment by jpoon** [comment]
Upstream issue. See the fix listed here: https://github.com/VSCodeVim/Vim/issues/2185

**Comment by jpoon** [comment]
You've tried https://github.com/VSCodeVim/Vim/issues/2185#issuecomment-348047731 and it doesn't work? @jenmud

**Comment by jenmud** [comment]
Yes @jpoon I did try [#2185 (comment)](https://github.com/VSCodeVim/Vim/issues/2185#issuecomment-348047731) that and unfortunately it still did not resolve my issue.

**Comment by jenmud** [comment]
@jpoon is there any more progress on the following or anything else that I can try?

**Comment by jpoon** [comment]
99.9% of the cases I've heard of this occurring is resolved by https://github.com/VSCodeVim/Vim/issues/2185#issuecomment-348047731. ie, deleting the `vscodevim` folder in your:

* Windows %USERPROFILE%\.vscode\extensions
* Mac $HOME/.vscode/extensions
* Linux $HOME/.vscode/extensions

And then re-installing the extension. Otherwise, you can try installing the extension manually by downloading one of the vsix here https://github.com/VSCodeVim/Vim/releases
