### ISSUE TITLE
VSCodeVim is locking up.

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#2564]
I'm on latest. VSCodeVim is randomly locking up and not accepting any keyboard inputs. This began happening on the most recent version.

**Comment by xconverge** [comment]
Anything in the developer tools window that might help?

**Comment by johnfn** [comment]
Heh, I didn't know there was a way to get into dev tools from normal vscode. I'll be sure to check next time.

**Comment by mirago** [comment]
Same thing happening for me, except that it only started to happen when I enabled second input source (second language) on my mac.

**Comment by xconverge** [comment]
Are either of you using neovim integration?

I just encountered this, I can run everything fine until I run a command, then I get

```
rror: spawn nvim ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by mirago** [comment]
I'm not using neovim, it's basically just a fresh install with this vim plugin. I cannot see any errors in the console, though.

**Comment by Poltergeist** [comment]
I am using the neovim integration. But this could be a thing. I think the integration stops working most of the time right after I ran a command.

**Comment by johnfn** [comment]
Got it to happen again. Here's the relevant (I assume) parts of the console:

```
[Extension Host] invalid value for set cursor position. This is probably bad?
2/private/var/folders/9x/7mr5rk450cg30w3011ls_2yd7myl0q/T/AppTranslocation/7…dio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:253 [Extension Host] TypeError: Cannot read property 'document' of undefined
	at Function.getLineCount (/Users/grantm/.vscode/extensions/vscodevim.vim-0.11.5/out/src/textEditor.js:118:46)
	at ModeHandler.<anonymous> (/Users/grantm/.vscode/extensions/vscodevim.vim-0.11.5/out/src/mode/modeHandler.js:484:58)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/grantm/.vscode/extensions/vscodevim.vim-0.11.5/out/src/mode/modeHandler.js:4:58)
	at <anonymous>
```

And, interestingly, here's what the status bar shows:

![image](https://user-images.githubusercontent.com/167745/39553743-fb70e0ca-4e23-11e8-9491-324afb50e169.png)

It has accepted the first g, but subsequent keypresses do not add any more characters to the status bar.

**Comment by johnfn** [comment]
Happened again, same exact output, down to the g in the status bar.

**Comment by markhagemann** [comment]
I am experiencing the same issue with a fresh install and no neovim setup on windows 64bit VSCode.

**Comment by Chillee** [comment]
@johnfn Do you know what keypresses you typed to get in that state?

In general, I think there's a bunch of invalid states that we allow that we shouldn't be, but I wasn't aware that they would lock up VSCodeVim.

**Comment by johnfn** [comment]
Finally figured it out, it's when you do gd and VSCodeVim doesn't find the definition in time.

**Comment by RemLampa** [comment]
Weird, I enabled VSCodeVim again today and it's working fine now. Will report back in if the issue reoccurs. 😀

**Comment by aardvarkk** [comment]
I am seeing this issue and it's reproducible. When I type a period on a certain line, it stops me from being able to type anything else. I can still select all and tab/untab, but the keyed entry is gone. Disabling the Vim extension fixes the problem. I don't see anything particularly helpful in the developer console.

**Comment by johnfn** [comment]
@aardvarkk if it's reproducible, could you provide reproduction steps please?

**Comment by aardvarkk** [comment]
Note that I also have the extensions Ruby 0.20.0 and Rails 0.8.1 installed.

1. Create a new file
2. Go to insert mode
3. Paste the following: `Tasks::CorrectStartAndEndForUnavailables.run(unavailables)`
3. Save as a Ruby file (I call mine `test.rb`)
4. Back in command mode, press `A` to append at the end of the line
5. Type a `.` to chain another method on the end
6. My text input locks up completely at this point

It seems to be some kind of intellisense-related thing. I see "Code Helper" go up to 100% CPU, and I'm unable to type for about 10-15 seconds.

**Comment by shawnaxsom** [comment]
This may or may not be related to #2021. I posted a few findings there, and I will be looking into making at least one optimization, if I find a good solution.

@aardvarkk Regarding `intellisense-related thing`, we were assuming that is one cause as well. We saw a lot of processing time on `net.js onread`, and we assumed that was reading for intellisense or other metadata uses as we typed. `Import Cost` extension made it worse for me, though we are able to replicate issues without it. I'm not sure whether Ruby and Rails extensions would exacerbate the issue or not.
