### ISSUE TITLE
tab.test.ts fails on Windows

### ISSUE THREAD

**Issue by KamikazeZirou** [VSCodeVim/Vim#2650]
**BUG REPORT**:

**What happened**:
tab.test.ts fails on Windows when the test of VSCodeVim is run.
The following error occurs.

>   1) cmd_line tab
>        tabe with absolute path when not in workspace opens file:
> 
>       AssertionError: Opened wrong file
>       + expected - actual
> 
>       -c:\Users\kamikaze\AppData\Local\Temp\pmlqsyuhc
>       +/C:/Users/kamikaze/AppData/Local/Temp/pmlqsyuhc
> 
>       at Object.<anonymous> (D:\kamikaze\workspace\Vim\test\cmd_line\tab.test.ts:47:14)
>       at Generator.next (&lt;anonymous&gt;)
>       at fulfilled (D:\kamikaze\workspace\Vim\out\test\cmd_line\tab.test.js:4:58)
>       at &lt;anonymous&gt;

**What did you expect to happen**:
tab.test.ts passes on Windows.

**How to reproduce it (as minimally and precisely as possible)**:
Run the test of  VSCodeVim.

**Environment**:

- Extension (VsCodeVim) version:0.11.6
- VSCode version:1.23.0
- OS version:Windows 10 Home, version 1803

**Comment by KamikazeZirou** [comment]
The cause is as follows.

1. Drive letters are different.  Expected drive letter is 'c' but actual drive letter is 'C'.
1. Path separator are different.
