### ISSUE TITLE
Vim extension stops working

### ISSUE THREAD

**Issue by ilteris** [VSCodeVim/Vim#2873]
I love this extension, 

I am on a mac, 1.25.1 VSC. 

Here's the error stack, let me know if you need more info please. 

[Extension Host] Here is the error stack:  TypeError: key.startsWith is not a function
	at Function.isSurroundedByAngleBrackets (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/src/configuration/notation.js:33:20)
	at Function.NormalizeKey (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/src/configuration/notation.js:12:19)
	at remapping.before.forEach (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/src/configuration/configuration.js:147:105)
	at Array.forEach (native)
	at Configuration.reload (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/src/configuration/configuration.js:147:38)
	at new Configuration (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/src/configuration/configuration.js:120:14)
	at Object.<anonymous> (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/src/configuration/configuration.js:286:25)
	at Object.<anonymous> (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/src/configuration/configuration.js:290:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/src/actions/base.js:3:25)
	at Object.<anonymous> (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/src/actions/base.js:179:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/src/actions/include-all.js:3:1)
	at Object.<anonymous> (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/src/actions/include-all.js:18:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/extension.js:16:1)
	at Object.<anonymous> (/Users/ikaplan/.vscode/extensions/vscodevim.vim-0.15.3/out/extension.js:295:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:30:770)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:790:186
	at t._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:790:298)
	at t._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:789:187)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:787:48)
	at e._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:452:188)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:451:757
	at Array.map (native)
	at e._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:451:732)
	at e.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:450:14)
	at t.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:787:412)
	at t.handleEagerExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:811:31)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:810:189
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:729)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:81:61)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:866)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:307)
	at e.open (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:112:607)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:787:86
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:729)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:81:61)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:866)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:307)
	at c (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:85:785)
	at $.then.o.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:85:999)
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:729)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:81:61)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:866)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:307)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:116:905
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:149:444
	at LOOP (fs.js:1728:14)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by ilteris** [comment]
This is my only vim setting:

```shell
 "vim.cursorStylePerMode": {
        "normal": "block",
        "insert": "line-thin",
        "replace": "block-outline"
    },
    "vim.leader": "space",
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                [
                    "<alt>",
                    "up"
                ],
            ],
            "commands": [
                "editor.action.moveLinesUpAction",
            ]
        },
        {
            "before": [
                [
                    "<alt>",
                    "down"
                ],
            ],
            "commands": [
                "editor.action.moveLinesDownAction",
            ]
        },
    ],
    "vim.debug.loggingLevel": "error"

```

**Comment by xmbhasin** [comment]
You've got an extra array in your command remappings (eg `"before: [[]]"` should be changed to `"before":[]`). Also just to note, <alt+up> and <alt+down> work without any special settings for me for moving lines up and down.
