### ISSUE TITLE
Broken on Insiders build

### ISSUE THREAD

**Issue by tylerthehaas** [VSCodeVim/Vim#3119]
**Describe the bug**
upgraded to the latest version of insiders build. 

Version 1.29.0-insider (1.29.0-insider)
1358e903716cf77711493770d63dde1ea178a73e

**To Reproduce**
Steps to reproduce the behavior: open vscode insiders try to go to normal mode. No modes will be available. Will just behave as if no vim extension is installed.

**Expected behavior**
all vim keybindings are available

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.9
- VSCode version: Version 1.29.0-insider (1.29.0-insider)
1358e903716cf77711493770d63dde1ea178a73e
- OS: Mac OS High Sierra 10.13.3

**Additional context**
I attempted to uninstall and reinstall plugin but that had no effect.

**Comment by nebenjamin** [comment]
I'm having the same issue.

Version: 1.29.0-insider (system setup)
Commit: 1358e903716cf77711493770d63dde1ea178a73e
Date: 2018-10-08T05:16:11.119Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Here is the error stack:
```
TypeError: Cannot read property 'prototype' of undefined
    at runInContext (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\node_modules\promised-neovim-client\node_modules\lodash\index.js:718:28)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\node_modules\promised-neovim-client\node_modules\lodash\index.js:12320:11)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\node_modules\promised-neovim-client\node_modules\lodash\index.js:12351:3)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\node_modules\promised-neovim-client\node_modules\lodash\index.js:12353:3)
    at Module.i._compile (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:268)
    at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:548)
    at Module.require (module.js:586:17)
    at n (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\node_modules\promised-neovim-client\index.js:7:11)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\node_modules\promised-neovim-client\index.js:235:3)
    at Module.i._compile (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:268)
    at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:548)
    at Module.require (module.js:586:17)
    at n (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\neovim\neovim.js:15:34)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\neovim\neovim.js:152:3)
    at Module.i._compile (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:268)
    at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:548)
    at Module.require (module.js:586:17)
    at n (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\state\vimState.js:12:18)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\state\vimState.js:181:3)
    at Module.i._compile (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:268)
    at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:548)
    at Module.require (module.js:586:17)
    at n (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\actions\motion.js:28:20)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\actions\motion.js:2299:3)
    at Module.i._compile (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:268)
    at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:548)
    at Module.require (module.js:586:17)
    at n (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\actions\textobject.js:23:18)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\actions\textobject.js:654:3)
    at Module.i._compile (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:268)
    at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:548)
    at Module.require (module.js:586:17)
    at n (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\actions\operator.js:28:22)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\actions\operator.js:979:3)
    at Module.i._compile (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:268)
    at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:548)
    at Module.require (module.js:586:17)
    at n (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\actions\include-all.js:4:1)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\src\actions\include-all.js:18:3)
    at Module.i._compile (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:268)
    at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:548)
    at Module.require (module.js:586:17)
    at n (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:808)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\extension.js:16:1)
    at Object.<anonymous> (C:\Users\nbenjamin\.vscode-insiders\extensions\vscodevim.vim-0.16.9\out\extension.js:321:3)
    at Module.i._compile (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.t._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:268)
    at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:548)
    at Module.require (module.js:586:17)
 (at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:295:77)
```

**Comment by ryanponce** [comment]
It's working again for me now.

**Comment by xconverge** [comment]
Looks like a fix was pushed
