### ISSUE TITLE
Code Action not working when using Vim mappings

### ISSUE THREAD

**Issue by naoric** [VSCodeVim/Vim#3160]
**Describe the bug**
When I map this keyboard shortcut:
```
"vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": ["space"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.codeAction",
          "args": {
            "kind": "refactor.extract.function",
            "apply": "first"
          }
        }
      ]
    },
```
And while editing in visual mode when I type `space` I see 'No code actions available' while it should extract the expression into a function/method

This is the exception I see:
```
TypeError: Cannot read property 'edit' of undefined
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2058:804
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:174:439
    at Object.o.__generator.a.label [as next] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:174:544)
    at r (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:173:686)
    at new Promise (<anonymous>)
    at r (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:173:463)
    at T (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2058:714)
    at e._onApplyCodeAction (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2061:374)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2060:442
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)"
```

When I use quick fix popup it works.

**To Reproduce**

1. Go to settings
2. Add the key mapping described above (happens with other code actions as well)
3. Open any JS file
4. Change into visual mode
5. Select an expression 
4. Type `space`

**Expected behavior**
Code Actions should work when in visual mode and extracting functions

**Screenshots**
![image](https://user-images.githubusercontent.com/2399935/47419605-397e4980-d785-11e8-8455-6d17d4c97e9f.png)

**Environment (please complete the following information):**
- Extension Name: vim
- Extension Version: 0.16.11
- OS Version: Darwin x64 18.0.0
- VSCode version: 1.28.2

**Additional context**
I tried to disable all other extensions just to make sure that the root cause is Vim.

This is my settings file:
```
// Place your settings in this file to overwrite the default settings
{
  "editor.fontLigatures": true,
  "editor.fontFamily": "Monaco",
  "rest-client.enableTelemetry": false,
  "editor.fontSize": 13.5,
  "editor.suggestSelection": "recentlyUsed",
  "search.location": "panel",
  "npm.packageManager": "npm",
  "npm.enableScriptExplorer": true,
  "files.autoSave": "onFocusChange",
  "files.trimTrailingWhitespace": true,
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
  "path-intellisense.autoSlashAfterDirectory": true,
  "editor.acceptSuggestionOnEnter": "off",
  "postfix.customTemplates": [
    {
      "name": "dd",
      "description": "destructure expression",
      "body": "const { $0 } = {{expr}}",
      "when": ["expression", "function-call"]
    },
    {
      "name": "class",
      "description": "Make Class",
      "body": "class {{expr}} $1 {$0}",
      "when": []
    },
    {
      "name": "impd",
      "description": "Import this",
      "body": "import {{expr}} from '$0'",
      "when": ["expression", "function-call", "identifier", "unary-expression"]
    },
    {
      "name": "imp",
      "description": "Import this",
      "body": "import { {{expr}} } from '$0'",
      "when": ["expression", "function-call", "identifier", "unary-expression"]
    },
    {
      "name": "par",
      "description": "Add Parentheses",
      "body": "$0({{expr}})",
      "when": ["expression", "identifier", "unary-expression"]
    },
    {
      "name": "const",
      "description": "Const",
      "body": "const $0 = {{expr}}",
      "when": ["expression", "function-call", "identifier", "unary-expression"]
    },
    {
      "name": "dimp",
      "description": "Import default",
      "body": "import {{expr}} from '${1:{{expr}}}'$0",
      "when": ["expression", "identifier", "unary-expression"]
    },
    {
      "name": "fp",
      "description": "Import from lodash",
      "body": "import {{expr}} from 'lodash/fp/{{expr}}'$0",
      "when": ["expression", "function-call", "identifier", "unary-expression"]
    }
  ],
  "advancedNewFile.exclude": {
    "node_modules": true,
    "node_modules_electron": true,
    "dev": true,
    "dist": true
  },
  "vim.easymotion": true,
  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": ["r"],
      "after": ["$"]
    },
    {
      "before": ["tab"],
      "after": ["S", "(", "F", "(", "i"]
    },
    {
      "before": ["enter"],
      "after": [],
      "commands": [
        {
          "command": "turboConsoleLog.displayLogMessage"
        }
      ]
    },
    {
      "before": ["space"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.codeAction",
          "args": {
            "kind": "refactor.extract.function",
            "apply": "first"
          }
        }
      ]
    },
    {
      "before": ["("],
      "after": [],
      "commands": [
        {
          "command": "editor.action.codeAction",
          "args": {
            "kind": "refactor.extract.constant",
            "apply": "first"
          }
        }
      ]
    }
  ],
  "vim.insertModeKeyBindings": [
    {
      "before": ["<C-c>"],
      "after": ["<Esc>", "A", ",", "<CR>"]
    },
    {
      "before": ["j", "j"],
      "after": ["<Esc>"]
    },
    {
      "before": ["<A-j>"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.insertCursorAbove"
        }
      ]
    },
    {
      "before": ["<A-k>"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.insertCursorBelow"
        }
      ]
    }
  ],
  "vim.insertModeKeyBindingsNonRecursive": [
    {
      "before": ["\\"],
      "after": ["{"]
    }
  ],
  "vim.normalModeKeyBindings": [
    {
      "before": ["{"],
      "after": [],
      "commands": [{ "command": "workbench.action.navigateBack" }]
    },
    {
      "before": ["}"],
      "after": [],
      "commands": [{ "command": "workbench.action.navigateForward" }]
    },
    {
      "before": ["alt+]"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusNextGroup"
        }
      ]
    },
    {
      "before": ["alt+["],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusPrevGroup"
        }
      ]
    },
    {
      "before": ["R"],
      "after": ["v", "i", "("]
    },
    {
      "before": ["<C-l>"],
      "after": ["c", "t", "\""]
    },
    {
      "before": ["H"],
      "after": ["@", "q"]
    },
    {
      "before": ["M"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.codeAction",
          "args": {
            "kind": "refactor.inline.function"
          }
        }
      ]
    },
    {
      "before": ["space"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.codeAction",
          "args": {
            "kind": "quickfix",
            "apply": "first"
          }
        }
      ]
    },
    {
      "before": ["`"],
      "after": ["<leader>", "<leader>", "<leader>", "b", "d", "e"]
    },
    {
      "before": ["<C-2>"],
      "after": ["<leader>", "<leader>", "<leader>", "b", "d", "w"]
    },
    {
      "before": ["m"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.gotoSymbol"
        }
      ]
    },
    {
      "before": ["Z"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.goToDeclaration"
        }
      ]
    },
    {
      "before": ["="],
      "after": [],
      "commands": [
        {
          "command": "editor.action.codeAction",
          "args": {
            "kind": "refactor.extract.function",
            "apply": "first"
          }
        }
      ]
    },
    {
      "before": ["backspace"],
      "after": ["d", "a", "w"]
    },
    {
      "before": ["<M-S-e>"],
      "after": ["d", "t", ">"]
    },
    {
      "before": ["<M-S-d>"],
      "after": ["d", "t", "\""]
    },
    {
      "before": ["T"],
      "after": ["c", "i", "t"]
    },
    {
      "before": ["K"],
      "after": ["v", "$"]
    },
    {
      "before": ["E"],
      "after": ["d", "a", "p"]
    },
    {
      "before": ["tab"],
      "after": ["c", "i", "w"]
    },
    {
      "before": ["t"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.rename"
        }
      ]
    },
    {
      "before": ["f7"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.quickFix"
        }
      ]
    },
    {
      "before": ["C-i"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.togglePanel"
        }
      ]
    },
    {
      "before": ["("],
      "after": [],
      "commands": [
        {
          // "command": "editor.action.marker.next"
          "command": "workbench.action.showCommands"
          // "args": {
          //   "kind": "refactor.extract.constant",
          //   "apply": "first"
          // }
        }
      ]
    },
    {
      "before": ["<M-A-n>"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.codeAction",
          "args": {
            "kind": "refactor.inline.variable"
          }
        }
      ]
    },
    {
      "before": ["J"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.joinLines"
        }
      ]
    },
    {
      "before": ["L"],
      "after": ["d", "d"]
    },
    {
      "before": ["\n"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.quickOpen"
        }
      ]
    },
    {
      "before": ["e"],
      "after": ["^"]
    },
    {
      "before": ["r"],
      "after": ["$"]
    },
    {
      "before": ["z"],
      "after": ["v", "i", "{"]
    },
    {
      "before": ["["],
      "after": [],
      "commands": [
        {
          "command": "cursorPageDown"
        }
      ]
    },
    {
      "before": ["]"],
      "after": [],
      "commands": [
        {
          "command": "cursorPageUp"
        }
      ]
    },
    {
      "before": ["X"],
      "after": ["c", "i", "("]
    },
    {
      "before": ["\""],
      "after": ["ci\""]
    }
  ],
  "sync.quietSync": false,
  "sync.askGistName": false,
  "editor.snippetSuggestions": "inline",
  "editor.detectIndentation": false,
  "editor.autoIndent": true,
  "emmet.showExpandedAbbreviation": "always",
  "editor.acceptSuggestionOnCommitCharacter": true,
  "vim.iskeyword": "/\\\"():,.;<>~!@#$%^&*|+=[]{}`?'",
  "vim.easymotionMarkerHeight": 20,
  "vim.easymotionMarkerBackgroundColor": "#dedede",
  "vim.easymotionMarkerYOffset": 0,
  "workbench.iconTheme": "eq-material-theme-icons",
  "window.zoomLevel": 0,
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/build": true,
    "**/.idea": true,
    "**/.DS_Store": true
  },
  "editor.multiCursorModifier": "ctrlCmd",
  "zenMode.fullScreen": false,
  "editor.minimap.enabled": true,
  "workbench.colorTheme": "Material Theme",
  "projectManager.sortList": "Recent",
  "projectManager.git.baseFolders": [
    "/Users/naoric/projects",
    "/Users/naoric/projects/go/src/github.com/AstralinkIO"
  ],
  "projectManager.git.maxDepthRecursion": 2,
  "projectManager.vscode.baseFolders": [
    "/Users/naoric/projects",
    "/Users/naoric/projects/go/src/github.com/AstralinkIO"
  ],
  "projectManager.vscode.maxDepthRecursion": 2,
  "explorer.confirmDelete": false,
  "explorer.confirmDragAndDrop": false,
  "gitlens.advanced.messages": {
    "suppressResultsExplorerNotice": true,
    "suppressShowKeyBindingsNotice": true,
    "suppressUpdateNotice": true
  },
  "sync.gist": "6aae8c4c1a938e95dff7d88ff9026d76",
  "sync.autoDownload": false,
  "sync.autoUpload": false,
  "sync.forceDownload": false,
  "vim.easymotionKeys": "hklyuiopnm,qwertzxcvbasdgjf.",
  "git.enableSmartCommit": true,
  "gitlens.keymap": "chorded",
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "emmet.triggerExpansionOnTab": true,
  "workbench.editor.showTabs": false,
  "html.autoClosingTags": true,
  "emmet.preferences": {
    "profile.allowCompactBoolean": true
  },
  "sync.removeExtensions": true,
  "sync.syncExtensions": true,
  "editor.roundedSelection": false,
  "emmet.excludeLanguages": ["javascript"],
  "workbench.fontAliasing": "auto",
  "gitlens.historyExplorer.enabled": false,
  "typescript.preferences.quoteStyle": "single",
  "git.autofetch": true,
  "workbench.colorCustomizations": {
    "activityBarBadge.background": "#C6FF00",
    "list.activeSelectionForeground": "#C6FF00",
    "list.inactiveSelectionForeground": "#C6FF00",
    "list.highlightForeground": "#C6FF00",
    "scrollbarSlider.activeBackground": "#C6FF0050",
    "editorSuggestWidget.highlightForeground": "#C6FF00",
    "textLink.foreground": "#C6FF00",
    "progressBar.background": "#C6FF00",
    "pickerGroup.foreground": "#C6FF00",
    "tab.activeBorder": "#C6FF00",
    "notificationLink.foreground": "#C6FF00",
    "editorWidget.border": "#C6FF00",
    "statusBar.background": "#005f5f",
    "statusBar.noFolderBackground": "#005f5f",
    "statusBar.debuggingBackground": "#005f5f"
  },
  "materialTheme.accent": "Acid Lime",
  "vim.enableNeovim": true,
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/.vscode": true,
    "**/.idea": true
  },
  "prettier.disableLanguages": [],
  "editor.formatOnSave": true,
  "postfix.languages": ["javascript", "typescript", "vue"],
  "prettier.jsxBracketSameLine": true,
  "prettier.singleQuote": true,
  "window.nativeTabs": true,
  "editor.formatOnType": true,
  "editor.tabSize": 2,
  "javascript.updateImportsOnFileMove.enabled": "always",
  // "vim.statusBarColorControl": true,
  "editor.suggest.localityBonus": true,
  "editor.tabCompletion": "on"
}

```

**Comment by naoric** [comment]
This is an issue with VS Code, not with Vim. sorry and thank you

**Comment by naoric** [comment]
https://github.com/Microsoft/vscode/issues/63101
