### ISSUE TITLE
Stopped working (VSCode 1.29.1, Vim 0.16.13)

### ISSUE THREAD

**Issue by eelco** [VSCodeVim/Vim#3227]
**Describe the bug**
The extension does not seem to work anymore.

**To Reproduce**

1.  Upgrade to latest VSCode
2. Upgrade to latest version of the plugin
3. ???

**Expected behavior**
It works.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.13
- VSCode version: 1.29.1
- OS: macOS 10.13.6

**Additional context**
It’s not showing in the running extensions list, but there is no output in the Extensions Host log other than:

```
[2018-11-28 12:18:16.148] [exthost] [info] ExtensionService#_doActivateExtension vscodevim.vim {"startup":true,"activationEvent":"*"}
[2018-11-28 12:18:16.148] [exthost] [info] ExtensionService#loadCommonJSModule /Users/eelco/.vscode/extensions/vscodevim.vim-0.16.13/out/extension
[2018-11-28 12:18:16.345] [exthost] [info] eager extensions activated
```

**Comment by nico29** [comment]
I have the same issue and here is a stacktrace from the devtools

```
 Here is the error stack:  Error: Cannot find module 'lodash'
	at Function.Module._resolveFilename (module.js:543:15)
	at Function.Module._load (module.js:473:25)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:713:896)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:885)
	at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/nicolas/.vscode/extensions/vscodevim.vim-0.16.13/out/src/taskQueue.js:11:11)
	at Object.<anonymous> (/Users/nicolas/.vscode/extensions/vscodevim.vim-0.16.13/out/src/taskQueue.js:85:3)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:713:896)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:885)
	at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/nicolas/.vscode/extensions/vscodevim.vim-0.16.13/out/src/configuration/configuration.js:19:21)
	at Object.<anonymous> (/Users/nicolas/.vscode/extensions/vscodevim.vim-0.16.13/out/src/configuration/configuration.js:317:3)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:713:896)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:885)
	at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/nicolas/.vscode/extensions/vscodevim.vim-0.16.13/out/src/actions/base.js:3:25)
	at Object.<anonymous> (/Users/nicolas/.vscode/extensions/vscodevim.vim-0.16.13/out/src/actions/base.js:181:3)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:713:896)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:885)
	at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/nicolas/.vscode/extensions/vscodevim.vim-0.16.13/out/src/actions/include-all.js:3:1)
	at Object.<anonymous> (/Users/nicolas/.vscode/extensions/vscodevim.vim-0.16.13/out/src/actions/include-all.js:18:3)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:713:896)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:885)
	at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/nicolas/.vscode/extensions/vscodevim.vim-0.16.13/out/extension.js:16:1)
	at Object.<anonymous> (/Users/nicolas/.vscode/extensions/vscodevim.vim-0.16.13/out/extension.js:331:3)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:713:896)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:677:885)
	at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:31:146)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:704:967
	at t._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:705:56)
	at t._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:703:854)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:701:644)
	at e._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:309:880)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:309:497
	at Array.map (<anonymous>)
	at e._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:309:472)
	at e.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:307:626)
	at t.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:702:48)
	at t.handleEagerExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:709:553)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:708:745
	at Object.g [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:807)
	at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:88:85)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:89:932)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:89:373)
	at e.open (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:116:340)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:701:682
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jpoon** [comment]
See https://github.com/VSCodeVim/Vim/issues/2519

**Comment by nico29** [comment]
Thanks @jpoon it worked in my case 👍
