### ISSUE TITLE
Extension crash or hangs when failing to call nvim

### ISSUE THREAD

**Issue by rodcloutier** [VSCodeVim/Vim#3433]
**Describe the bug**

vscode extension crash/hangs when failing to call `nvim`. Receive a `ENOENT` error.
Extension cannot be used anymore.

Console output:
```
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] Neovim: error: Error spawning neovim. Error=spawn /usr/local/bin/nvim ENOENT.
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:303
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2508 Neovim: Error spawning neovim. Error=spawn /usr/local/bin/nvim ENOENT.
t.onDidNotificationChange @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2508
2/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] Error: Unexpected SIGPIPE
	at process.on (/usr/share/code/resources/app/out/bootstrap.js:5:80)
	at emitNone (events.js:106:13)
	at process.emit (events.js:208:7)
	at Signal.process.on.wrap.onsignal (internal/process.js:208:44)
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:303
```
**To Reproduce**
1. Create new file
2. Type `:W`

**Expected behavior**
Vscode not freezing or crashing

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.5
- No other extension enabled
- Nvim:  0.3.3
- VSCode
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.19.15-300.fc29.x86_64

**Comment by bradamelton** [comment]
I am also experiencing this. It works for a few seconds after startup, then crashes and no typing is possible. Just started today.

**Comment by buwilliams** [comment]
+1

**Comment by jpoon** [comment]
1. Was neovim working before w/ vscodevim < 1.0.5?
2. Is this happening for all ex-commands?

**Comment by jpoon** [comment]
With nvim 0.3.3 and vscodevim (on master), I can't repro.

There's a scenario where this repros (extension gets stuck) when you have nvim misconfigured which I'll fix in a PR shortly.

**Comment by rodcloutier** [comment]
I can confirm that it was the case, my nvim path was wrong.
Thanks for the info/patch.

**Comment by dytra** [comment]
I reinstalled the extension and it fixes itself

**Comment by pokemonsta433** [comment]
Update to this: if your nvim is configured to run as administrator and you launch vscode as normal user, you get the same error message and behaviour. Possibly ensure that your nvim is not configured as administrator.
