### ISSUE TITLE
Master tests broken

### ISSUE THREAD

**Issue by sectioneight** [VSCodeVim/Vim#468]
Something broke today. I haven't run a bisect yet.

```
    at ModeHandler.executeOperator (/Users/aiden/src/vscode-vim/src/mode/modeHandler.ts:746:51)
    at ModeHandler.<anonymous> (/Users/aiden/src/vscode-vim/src/mode/modeHandler.ts:624:29)
    at undefined.next (native)
    at fulfilled (/Users/aiden/src/vscode-vim/src/mode/modeHandler.ts:1:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Error: what in god's name
    at ModeHandler.<anonymous> (/Users/aiden/src/vscode-vim/src/mode/modeHandler.ts:752:13)
    at undefined.next (native)
    at __awaiter (/Users/aiden/src/vscode-vim/src/mode/modeHandler.ts:1:14)
    at __awaiter (/Users/aiden/src/vscode-vim/src/mode/modeHandler.ts:1:14)
    at ModeHandler.executeOperator (/Users/aiden/src/vscode-vim/src/mode/modeHandler.ts:746:51)
    at ModeHandler.<anonymous> (/Users/aiden/src/vscode-vim/src/mode/modeHandler.ts:624:29)
    at undefined.next (native)
    at fulfilled (/Users/aiden/src/vscode-vim/src/mode/modeHandler.ts:1:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  1) will fail when ca( with no ()
Nothing matched!
```

**Comment by sectioneight** [comment]
Hmm, seems intermittent, master is mostly OK now.
