### ISSUE TITLE
Throw exceptions when run `ca( with no {}` test case

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#474]
### Technical details:

* VSCode Version: 1.4.0-Insiders
* VsCodeVim Version: Master Branch
* OS: Windows 10 Enterprise

Even though finally all test cases pass, I've seen following exceptions..
```
will fail when ca( with no {}
error.stack
Error: what in god's name
    at ModeHandler.<anonymous> (c:\Users\cici\code\Vim\src\mode\modeHandler.ts:788:13)
    at undefined.next (native)
    at __awaiter (c:\Users\cici\code\Vim\src\mode\modeHandler.ts:1:14)
    at __awaiter (c:\Users\cici\code\Vim\src\mode\modeHandler.ts:1:14)
    at ModeHandler.executeOperator (c:\Users\cici\code\Vim\src\mode\modeHandler.ts:782:51)
will fail when ca( with no () (1439ms)

```

**Comment by rebornix** [comment]
@sectioneight any idea on this one?

**Comment by sectioneight** [comment]
I've seen this as well. I think this was introduced in the "cancellation" code in #466 but haven't tracked it down yet

**Comment by johnfn** [comment]
I know why this is. It's actually not terrible, since the user won't notice at all. Still should be fixed at some point.

**Comment by rebornix** [comment]
This issue is tracked in #700.
