### ISSUE TITLE
Failed to handle key=u. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by eirianop** [VSCodeVim/Vim#5209]
**To Reproduce**

0. use vscode-insiders
1. install vim plugin (vscodevim.vim)
2. install .NET notebooks
3. create a .dib file 
4. create multiple code cells
5. add content to cells 
6. go to a previous cell and press u in command mode (undo in vim)
7. see error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=u. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/eper363/.vscode-insiders/extensions/vscodevim.vim-1.17.0/out/extension.js:9:508876)
	at h.setLastHistoryEndPosition (/Users/eper363/.vscode-insiders/extensions/vscodevim.vim-1.17.0/out/extension.js:9:516428)
	at F.runAction (/Users/eper363/.vscode-insiders/extensions/vscodevim.vim-1.17.0/out/extension.js:9:478631)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/eper363/.vscode-insiders/extensions/vscodevim.vim-1.17.0/out/extension.js:9:474707)
	at async F.handleKeyEvent (/Users/eper363/.vscode-insiders/extensions/vscodevim.vim-1.17.0/out/extension.js:9:471516)
	at async Object.promise (/Users/eper363/.vscode-insiders/extensions/vscodevim.vim-1.17.0/out/extension.js:9:235653)
	at async Object.runTasks (/Users/eper363/.vscode-insiders/extensions/vscodevim.vim-1.17.0/out/extension.js:9:621827)
```

</details>

**Comment by cmcginty** [comment]
+1
