### ISSUE TITLE
Failed to handle key=j. getLineLength() called with out-of-bounds line 105

### ISSUE THREAD

**Issue by terryrao** [VSCodeVim/Vim#5214]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=j. getLineLength() called with out-of-bounds line 105
	at Function.getLineLength (c:\Users\raow\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:22186)
	at l.getUpWithDesiredColumn (c:\Users\raow\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:11583)
	at l.getLeftThroughLineBreaks (c:\Users\raow\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:10833)
	at c:\Users\raow\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:475183
	at Array.map (<anonymous>)
	at F.runAction (c:\Users\raow\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:475130)
	at F.handleKeyAsAnAction (c:\Users\raow\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:474718)
	at F.handleKeyEvent (c:\Users\raow\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:471527)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (c:\Users\raow\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:235653)
	at async Object.runTasks (c:\Users\raow\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment]
What were you trying to do when this happened?
