### ISSUE TITLE
Forced by user

### ISSUE THREAD

**Issue by IPhoenixSuns** [VSCodeVim/Vim#5219]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Forced by user
	at F.handleKeyEvent (c:\Users\Phoenix\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:469806)
	at Object.promise (c:\Users\Phoenix\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:235661)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (c:\Users\Phoenix\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:621827)
```

</details>

**Comment by IPhoenixSuns** [comment]
Hello! I have binded ii to escape from insert mode. But recently it works bad and my vscode freeze for a while with error from vim. Check 
 error above. My settings.json: 
  "vim.insertModeKeyBindings": [
      {
      "before": ["i", "i"],
      "commands": ["extension.vim_escape"]
    },
  ],

**Comment by berknam** [comment]
Why are you using `"commands": ["extension.vim_escape"]`? Your keybinding should be:
```json
"vim.insertModeKeyBindings": [
    {
        "before": ["i", "i"],
        "after": ["<Esc>"]
    },
],
```

**Comment by IPhoenixSuns** [comment]
Thanks a lot! I don't know, maybe I copied from somewhere!
