### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by CuongTrinh1280** [VSCodeVim/Vim#5224]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
	at t.ExtHostTextEditor._applyEdit (c:\Users\LENOVO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:717)
	at t.ExtHostTextEditor.edit (c:\Users\LENOVO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:252)
	at F.executeCommand (c:\Users\LENOVO\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:482747)
	at F.runAction (c:\Users\LENOVO\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:475391)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (c:\Users\LENOVO\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:474707)
	at async F.handleKeyEvent (c:\Users\LENOVO\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:471516)
	at async Object.promise (c:\Users\LENOVO\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:231560)
	at async Object.runTasks (c:\Users\LENOVO\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:621827)
```

</details>

**Comment by J-Fields** [comment]
Can you reliably reproduce?
