### ISSUE TITLE
Failed to handle key=p. v.split is not a function

### ISSUE THREAD

**Issue by carlesba** [VSCodeVim/Vim#5239]
**To Reproduce**

1.  Use multiple selection (cmd+D)
2.  press ESC to enter Visual Mode
3.  press yy to copy the hole line
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. v.split is not a function
	at n.exec (/Users/carles.ballester/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:409622)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async n.execCount (/Users/carles.ballester/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:37418)
	at async n.execCount (/Users/carles.ballester/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:411621)
	at async F.runAction (/Users/carles.ballester/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:475314)
	at async F.handleKeyAsAnAction (/Users/carles.ballester/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:474707)
	at async F.handleKeyEvent (/Users/carles.ballester/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:471516)
	at async Object.promise (/Users/carles.ballester/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:235653)
	at async Object.runTasks (/Users/carles.ballester/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:621827)
```

</details>

**Comment by sql-koala** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Use multiple selection (cmd+D)
> 2. press ESC to enter Visual Mode
> 3. press yy to copy the hole line
> 4. See error

Do you mean:
Step 4: paste with p?
Because in steps 1-3, there is no key p. I can repro with: Step 4 p.

I think this is connected to #4562

**Comment by loganaaaflag** [comment]
FWIW I'm having this issue too. 

For me it happens when I've copied text using multiple cursors, then try to paste the selected text *without* having the same number of cursors as paste targets - either too few or too many. Here's  an example.

![example](https://user-images.githubusercontent.com/55156743/95502441-b0a34d00-095e-11eb-91f4-d582bc6e5235.gif)

**Comment by donnol** [comment]
I get the problem same with @loganaaaflag

**Comment by J-Fields** [comment]
I'm not able to reproduce. Do you have `p` mapped to `gp` or `]p` or something? Does it matter how you yank the text (`yy`, `yw`, `yiw`, `vwy`, etc.)?

**Comment by loganaaaflag** [comment]
I don't have `p` remapped to anything, and it doesn't seem to matter which method I use to yank the text - they all throw. I do have a couple plugins enabled though (sneak, CamelCaseMotion, and a few others), I'm not sure if that has any effect. 

If the plugin has some sort of debug logger I can turn on and submit, I'm happy to do so!
Can also post any settings if needed as well.

Thanks!

As an aside, to clarify the gif I posted, the steps for me were exactly:

1) In visual mode, create new cursors using `Alt + Ctrl + Down`
2) Yank the text from the lines using `yy`
3) Move the (now single) cursor to a new line
4) Paste the yanked text using `p`
5) `Failed to handle key=p. v.split is not a function` error is thrown
