### ISSUE TITLE
Failed to handle key=p. v.split is not a function

### ISSUE THREAD

**Issue by npc-vicki** [VSCodeVim/Vim#5244]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. v.split is not a function
	at n.exec (/Users/vicki/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:409622)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async n.execCount (/Users/vicki/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:37418)
	at async n.execCount (/Users/vicki/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:411621)
	at async F.runAction (/Users/vicki/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:475314)
	at async F.handleKeyAsAnAction (/Users/vicki/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:474707)
	at async F.handleKeyEvent (/Users/vicki/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:471516)
	at async Object.promise (/Users/vicki/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:235653)
	at async Object.runTasks (/Users/vicki/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:621827)
```

</details>

**Comment by npc-vicki** [comment]
Oops same as https://github.com/VSCodeVim/Vim/issues/5239, closing
