### ISSUE TITLE
Failed to handle key=<BS>. [vscodevim.vim]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscodevim.vim

### ISSUE THREAD

**Issue by GChasing** [VSCodeVim/Vim#5264]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. [vscodevim.vim]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscodevim.vim
	at a (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:509:620)
	at Object.t.checkProposedApiEnabled (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:509:982)
	at x.getConfiguration (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:699:923)
	at Object.getConfiguration (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:791:3)
	at h.getConfiguration (/home/chasing/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:6027)
	at Function.shouldDeleteMatchingBracket (/home/chasing/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:93767)
	at Function.immediateMatchingBracket (/home/chasing/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:93884)
	at c (/home/chasing/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:481980)
	at /home/chasing/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:482860
	at t.ExtHostTextEditor.edit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:503:191)
	at F.executeCommand (/home/chasing/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:482834)
	at F.runAction (/home/chasing/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475478)
	at async F.handleKeyAsAnAction (/home/chasing/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/chasing/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/chasing/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/chasing/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment]
What were you doing when this happened?

**Comment by Serubin** [comment]
Also having this error when I try to do any vim command: enter insert, `dd`, enter visual, etc

**Comment by J-Fields** [comment]
What VSCode version are you running?

**Comment by Serubin** [comment]
Opened a ticket with actual details here: https://github.com/VSCodeVim/Vim/issues/5342

**Comment by Serubin** [comment]
Added vscode version in other ticket -  1.42.0

**Comment by J-Fields** [comment]
Any reason you're using such an old version?

**Comment by Serubin** [comment]
Heh, apparently VSCode doesn't know how to check for updates. Will see if that resolves.

**Comment by Serubin** [comment]
@J-Fields That fixed it. Can probably close out this ticket.
