### ISSUE TITLE
Failed to handle key=d. getLineLength() called with out-of-bounds line 25

### ISSUE THREAD

**Issue by barangilani** [VSCodeVim/Vim#5266]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. getLineLength() called with out-of-bounds line 25
	at Function.getLineLength (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getLineEnd (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:13777)
	at jt.exec (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:124634)
	at jt.execCount (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37019)
	at F.runAction (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475409)
	at F.handleKeyAsAnAction (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at Object.promise (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235748)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/Users/baran/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by barangilani** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **VSCodeVim version**: 1.17.1
> 
> Stack trace
