### ISSUE TITLE
Failed to handle key=d. Illegal value for `line`

### ISSUE THREAD

**Issue by Giraffeprogram** [VSCodeVim/Vim#5269]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. Illegal value for `line`
	at d._lineAt (/private/var/folders/gl/rb3xn8bn02n2bkz5nkmf67z40000gn/T/AppTranslocation/39739A84-B06A-4090-A557-17AE083A2A9F/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:535:222)
	at Object.lineAt (/private/var/folders/gl/rb3xn8bn02n2bkz5nkmf67z40000gn/T/AppTranslocation/39739A84-B06A-4090-A557-17AE083A2A9F/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:534:181)
	at Function.getLineAt (/Users/osagieosahenagharu/Downloads/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22450)
	at ue (/Users/osagieosahenagharu/Downloads/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:197467)
	at n.execActionWithCount (/Users/osagieosahenagharu/Downloads/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:198006)
	at F.executeMovement (/Users/osagieosahenagharu/Downloads/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:479443)
	at F.runAction (/Users/osagieosahenagharu/Downloads/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475347)
	at F.handleKeyAsAnAction (/Users/osagieosahenagharu/Downloads/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474805)
	at F.handleKeyEvent (/Users/osagieosahenagharu/Downloads/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at Object.promise (/Users/osagieosahenagharu/Downloads/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235748)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/Users/osagieosahenagharu/Downloads/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment]
What were you doing when this happened? Can you reproduce?
