### ISSUE TITLE
Cannot read property 'visibleRanges' of undefined

### ISSUE THREAD

**Issue by binhnguyenduc** [VSCodeVim/Vim#5298]
**To Reproduce**

Update VSCode to 1.49.2

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'visibleRanges' of undefined
	at F.updateView (/Users/binhnd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:489831)
	at _ (/Users/binhnd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/binhnd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235688)
	at async Object.runTasks (/Users/binhnd/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment]
Duplicate of #5256; if you can reproduce, please post steps there
