### ISSUE TITLE
vimrc: check if running in vscode or not

### ISSUE THREAD

**Issue by vegerot** [VSCodeVim/Vim#5317]
**Describe the bug**
I have a certain mapping in my `vimrc` (`nmap gh :diffget //2 \| diffupdate<CR>`) that is wreaking havoc when used inside vscode.  How can I not use this mapping when in VSCode?

**To Reproduce**

1.  add `nmap gh :diffget //2 \| diffupdate<CR>` to your vimrc
2.  In VSCode, try to get hover info for a symbol
3.  Don't profit :( 

**Expected behavior**
A variable to be set inside the Neovim core environment that can be checked, such as 
`If !has('vscode')`

**Screenshots**
<img width="809" alt="image" src="https://user-images.githubusercontent.com/5297725/94855573-b9df6780-03fc-11eb-899e-38623a0d7727.png">
```log
[Extension Host] Neovim: debug: version: 0.4.4 (at t.ConsoleForElectron.log (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:371425))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{message: "request -> neovim.api.nvim_get_current_buf", level: "debug"}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{level: "info", message: "handleNotification: "}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{message: "response -> neovim.api.nvim_get_current_buf: [object Object]", level: "debug"}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{message: "request -> neovim.api.nvim_set_option", level: "debug"}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{message: "response -> neovim.api.nvim_set_option: null", level: "debug"}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{message: "request -> neovim.api.nvim_buf_set_lines", level: "debug"}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{message: "response -> neovim.api.nvim_buf_set_lines: null", level: "debug"}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{message: "request -> neovim.api.nvim_call_function", level: "debug"}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{level: "info", message: "handleNotification: "}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{message: "response -> neovim.api.nvim_call_function: 0", level: "debug"}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{message: "request -> neovim.api.nvim_call_function", level: "debug"}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
console.ts:137 [Extension Host] [winston] Attempt to write logs with no transports %j 
{level: "info", message: "handleNotification: "}
 (at t._transform (/Users/maxcoplan/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:609986))
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: latest
- VSCode version: latest
- OS: macOS

**Additional context**

**Comment by J-Fields** [comment]
Yeah, this is planned but frankly probably won't happen any time particularly soon because it requires more advanced support of vimscript

**Comment by vegerot** [comment]
So today, how can I check?

**Comment by vegerot** [comment]
How about we set an environment variable that we can check?

**Comment by J-Fields** [comment]
You could probably hack something together that would evaluate in VSCodeVim and not in vim, but since we don't yet understand `If` in vimscript, it's a bit trickier to do the opposite. My recommendation would be to put any vim-only config in a separate file and `source` that from your shared `.vimrc`. That won't get evaluated in VSCodeVim because we don't support `source` yet either 🙂 (see #5542).

**Comment by vegerot** [comment]
Since I use `vim-plug`, my hack is to check if `plug` exists.

```vim
" `gh` is the hover action in VSCode
if (!exists('plug'))
  nmap gh :diffget //2 \| diffupdate<CR>
endif
nmap gl :diffget //3 \| diffupdate<CR>
```
