### ISSUE TITLE
VSCode not working: command 'type' already exists at _.registerCommand

### ISSUE THREAD

**Issue by elefthei** [VSCodeVim/Vim#5318]
**Describe the bug**
VIM mode, escape does not work. Can type normally while in "Normal" mode. No vim key combinations work.
Specific error in Developer console:

`console.ts:137 [Extension Host] stack trace: Error: command 'type' already exists	at _.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:674:270)	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:977:119)	at R (/Users/lef/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230907)	at Object.t.activate (/Users/lef/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235625)
t.log @ console.ts:70
`

**Expected behavior**
The plugin works and I can use VIM mode.

** Environment **
On MacOSX Catalina,
VSCodeVIM 0.17.1,
VSCode 1.49.2

**Comment by J-Fields** [comment]
Is this still an issue?

**Comment by sbjessee** [comment]
I found the conflicting extension was `lak132.indent-to-bracket v1.2.2`

**Comment by shivanshu-semwal** [comment]
This is another conflicting extension - [https://github.com/AdamMaras/vscode-overtype](https://github.com/AdamMaras/vscode-overtype)
And this is the main issue for `type` [https://github.com/microsoft/vscode/issues/13441](https://github.com/microsoft/vscode/issues/13441)

**Comment by muthursyamburi** [comment]
> This is another conflicting extension - https://github.com/AdamMaras/vscode-overtype And this is the main issue for `type` [microsoft/vscode#13441](https://github.com/microsoft/vscode/issues/13441)

Thank you so much!!! I was hitting my head on why vim is not working fine and finally I could resolve it! Yes, overtype was the culprit for me, and I am now back into the happy world of VIM!!! Wowwwwww....
