### ISSUE TITLE
Failed to handle key=\. Invalid regular expression: /a\/: \ at end of pattern

### ISSUE THREAD

**Issue by jrdioko** [VSCodeVim/Vim#5325]
**To Reproduce**

1.  Use `<leader> <leader> /` to trigger easymotion search n-character mode
2. Type `a\`

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
SyntaxError: Failed to handle key=\. Invalid regular expression: /a\/: \ at end of pattern
	at new RegExp (<anonymous>)
	at f (/Users/username/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:97075)
	at t.SearchByNCharCommand.getMatches (/Users/username/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:98038)
	at F.updateView (/Users/username/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:493706)
	at F.handleKeyAsAnAction (/Users/username/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474893)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyEvent (/Users/username/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/username/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/username/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by Goddesen** [comment]
I have encountered this when trying to create my own EasyMotion commands building on top of `<leader> <leader> /`. The search term can be a regex, but I am not allowed to input anything that leads to a regex error, so character groups and capture groups and escaped characters don't work.

This issue is not a duplicate of #5665.
