### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by danielo515** [VSCodeVim/Vim#5346]
**To Reproduce**

1.  Use VSpaceCode vim
2.  Write a binding like the one specified below
3.  Execute it
4.  See error

```
  "vspacecode.bindingOverrides": [
    {
      "keys": ["w"],
      "name": "Write all",
      "type": "command",
      "command": "vim.remap",
      "args": {
        "commands": ["workbench.action.files.saveAll"]
      }
    }
]
```

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'startsWith' of undefined
    at Object.promise (/Users/danielo/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:236987)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.runTasks (/Users/danielo/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by danielo515** [comment]
Wrong mapping. Sory
