### ISSUE TITLE
Failed to handle key=l. Cannot read property 'searchString' of undefined

### ISSUE THREAD

**Issue by enriquebrosericus** [VSCodeVim/Vim#5351]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=l. Cannot read property 'searchString' of undefined
	at k.exec (c:\Users\edawg\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:436870)
	at k.execCount (c:\Users\edawg\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:1:37019)
	at F.runAction (c:\Users\edawg\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:475409)
	at F.handleKeyAsAnAction (c:\Users\edawg\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:474805)
	at F.handleKeyEvent (c:\Users\edawg\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (c:\Users\edawg\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
	at async Object.runTasks (c:\Users\edawg\.vscode\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment]
Can you reproduce?
