### ISSUE TITLE
Failed to handle key=<C-a>. Unexpected mode in IncrementDecrementNumberAction.getPositions()

### ISSUE THREAD

**Issue by JMBegue** [VSCodeVim/Vim#5397]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Unexpected mode in IncrementDecrementNumberAction.getPositions()
	at sr.getSearchRanges (/home/begue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:135804)
	at sr.exec (/home/begue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:133936)
	at sr.execCount (/home/begue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37468)
	at x.exec (/home/begue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:214331)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async x.execCount (/home/begue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37457)
	at async F.runAction (/home/begue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
	at async F.handleKeyAsAnAction (/home/begue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/home/begue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/home/begue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231560)
	at async Object.runTasks (/home/begue/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment]
What were you trying to do when this happened? Can you reproduce?

**Comment by J-Fields** [comment]
I believe this was fixed in a prior version - please let me know if you experience this again.
