### ISSUE TITLE
Forced by user

### ISSUE THREAD

**Issue by cehidalgo** [VSCodeVim/Vim#5419]
Hey o/

I actually don't know how to reproduce this, but I ended up taking on my daily use of the extension.

Thx for the attention.

--- This was generated after I clicked on the "Report Bug" button on the VSCode notification:

**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Forced by user
	at F.handleKeyEvent (/home/cadu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:469893)
	at Object.promise (/home/cadu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231568)
	at Object.runTasks (/home/cadu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621922)
	at Object.enqueueTask (/home/cadu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:622955)
	at T (/home/cadu/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:231538)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

</details>

**Comment by J-Fields** [comment]
@berknam This seems to be an uncaught `ForceStopRemappingError` - any idea why this might happen?

**Comment by berknam** [comment]
@cehidalgo Do you have any remap like this:
```
"vim.insertModeKeyBindings": [
  {
    "before": ["j", "j"],
    "commands": ["extension.vim_escape"]
  }
]
```

This happens because the command "extension.vim_escape" sends the `<Esc>` key to Vim as if the user pressed it and when we receive it the recursive remap is still going so it tries to cancel it self. But you're right in that it shouldn't leak the error like this. I have a fix for it, will push it soon.
