### ISSUE TITLE
Paste fails when yanked multiple selections (Failed to handle key=p. v.split is not a function)

### ISSUE THREAD

**Issue by andycmaj** [VSCodeVim/Vim#5461]
**To Reproduce**

1. `y` to yank multiple selections (after seleting multiple symbols)
2.  move to another editor
3.  `p` to paste
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. v.split is not a function
    at n.exec (/Users/ac/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:409709)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at n.execCount (/Users/ac/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37457)
    at n.execCount (/Users/ac/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:411708)
    at F.runAction (/Users/ac/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
    at F.handleKeyAsAnAction (/Users/ac/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/Users/ac/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/Users/ac/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/Users/ac/.vscode-insiders/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by andycmaj** [comment]
dupe of https://github.com/VSCodeVim/Vim/issues/5460
