### ISSUE TITLE
Failed to handle key=p. e.match is not a function

### ISSUE THREAD

**Issue by strozzi-diana** [VSCodeVim/Vim#5544]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. e.match is not a function
	at l.advancePositionByText (/Users/strozzi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:14025)
	at n.exec (/Users/strozzi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:409673)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.exec (/Users/strozzi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:413539)
	at async y.execCount (/Users/strozzi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37457)
	at async F.runAction (/Users/strozzi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
	at async F.handleKeyAsAnAction (/Users/strozzi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/strozzi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/strozzi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/strozzi/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment]
Can you reproduce?
