### ISSUE TITLE
Failed to handle key=o. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by ruiyotabby** [VSCodeVim/Vim#5614]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=o. Illegal argument: line must be non-negative
    at Object.t.illegalArgument (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new _ (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:513:364)
    at new _ (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:511:436)
    at new l (/home/karon/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:9299)
    at ft.execCount (/home/karon/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:112316)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (/home/karon/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
    at F.handleKeyAsAnAction (/home/karon/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/home/karon/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/home/karon/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/home/karon/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment]
I think this has been fixed, please create a new issue if it comes up again
