### ISSUE TITLE
Failed to handle key=u. The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined

### ISSUE THREAD

**Issue by yeasincode** [VSCodeVim/Vim#5625]
**To Reproduce**
when setting
   {
            "before": [
                "<leader>",
                "g",
                "u"
            ],
            "commands": [
                "java.action.navigateToSuperImplementation"
            ]
        }

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
	at Function.from (buffer.js:305:9)
	at t.StandardLanguageClient.<anonymous> (c:\Users\416\.vscode-insiders\extensions\redhat.java-0.70.0\dist\extension.js:15:79302)
	at Generator.next (<anonymous>)
	at c:\Users\416\.vscode-insiders\extensions\redhat.java-0.70.0\dist\extension.js:15:72286
	at new Promise (<anonymous>)
	at r (c:\Users\416\.vscode-insiders\extensions\redhat.java-0.70.0\dist\extension.js:15:72031)
	at c:\Users\416\.vscode-insiders\extensions\redhat.java-0.70.0\dist\extension.js:15:78660
	at _executeContributedCommand (c:\Users\416\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:701:753)
	at _doExecuteCommand (c:\Users\416\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:700:867)
	at _.executeCommand (c:\Users\416\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:700:773)
	at Object.executeCommand (c:\Users\416\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:996:29)
	at f.handleRemapping (c:\Users\416\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:501849)
	at f.sendKey (c:\Users\416\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:499795)
	at t.Remappers.sendKey (c:\Users\416\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:496237)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyEvent (c:\Users\416\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:471257)
	at async Object.promise (c:\Users\416\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:235740)
	at async Object.runTasks (c:\Users\416\.vscode-insiders\extensions\vscodevim.vim-1.17.1\out\extension.js:9:621914)
```

</details>

**Comment by mycf** [comment]
me too
