### ISSUE TITLE
Forced by user

### ISSUE THREAD

**Issue by mikedodge04** [VSCodeVim/Vim#5649]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Forced by user
	at F.handleKeyEvent (/home/mikedodge04/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:469893)
	at Object.promise (/home/mikedodge04/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235748)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/home/mikedodge04/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by mikedodge04** [comment]
but dial
