### ISSUE TITLE
Failed to handle key=e. Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by tranducngocmygit134** [VSCodeVim/Vim#5732]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=e. Cannot read property 'stop' of undefined
    at p.get cursorStopPosition [as cursorStopPosition] (/home/tdn/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:505145)
    at F.createUndoPointForBrackets (/home/tdn/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:494726)
    at F.runAction (/home/tdn/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:476613)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.handleKeyAsAnAction (/home/tdn/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
    at F.handleKeyEvent (/home/tdn/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
    at Object.promise (/home/tdn/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
    at Object.runTasks (/home/tdn/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by joshmu** [comment]
Resolved: #5736
