### ISSUE TITLE
Failed to handle key=p. Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jzz4012650** [VSCodeVim/Vim#5797]
**To Reproduce**

1. Select some text;
2. Press `y` to copy text;
3. Select some other text;
4. Press `cmd+d` to select more same text;
5. Press `p` to paste copied text to multi place;

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. Cannot read property 'split' of undefined
	at n.exec (/Users/jzz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:409709)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.exec (/Users/jzz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:413539)
	at async y.execCount (/Users/jzz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37457)
	at async F.runAction (/Users/jzz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:475401)
	at async F.handleKeyAsAnAction (/Users/jzz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:474794)
	at async F.handleKeyEvent (/Users/jzz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471603)
	at async Object.promise (/Users/jzz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/jzz/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by sql-koala** [comment]
Thanks for the steps to repro.
The issue is known, #5493 

I have given a temporary workaround here:
https://github.com/VSCodeVim/Vim/issues/5208#issuecomment-700243223
