### ISSUE TITLE
Failed to handle key=<C-h>. Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by d00m4n** [VSCodeVim/Vim#5829]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.2

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<C-h>. Cannot read property 'match' of undefined
	at Function.immediateMatchingBracket (c:\Users\dr_d00m4n\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:94241)
	at c (c:\Users\dr_d00m4n\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:481980)
	at c:\Users\dr_d00m4n\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:482860
	at t.ExtHostTextEditor.edit (c:\Users\dr_d00m4n\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:651:588)
	at F.executeCommand (c:\Users\dr_d00m4n\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:482834)
	at F.runAction (c:\Users\dr_d00m4n\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:475478)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (c:\Users\dr_d00m4n\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:474794)
	at async F.handleKeyEvent (c:\Users\dr_d00m4n\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:471603)
	at async Object.promise (c:\Users\dr_d00m4n\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:231560)
	at async Object.runTasks (c:\Users\dr_d00m4n\.vscode\extensions\vscodevim.vim-1.17.2\out\extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment]
Can you reproduce?
