### ISSUE TITLE
Failed to handle key=f. argument does not match one of these constraints: arg instanceof constraint, arg.constructor === constraint, nor constraint(arg) === true

### ISSUE THREAD

**Issue by marroquinsamy** [VSCodeVim/Vim#5830]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.2

<details><summary>Stack trace</summary>

```
Error: argument does not match one of these constraints: arg instanceof constraint, arg.constructor === constraint, nor constraint(arg) === true
    at l (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:288:8)
    at Object.t.validateConstraints (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:288:578)
    at e.handler (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1680:594)
    at d.invokeFunction (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1724:588)
    at u._tryExecuteCommand (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4151:37)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4150:774
```

</details>

**Comment by J-Fields** [comment]
Possibly related to #5819?
