### ISSUE TITLE
Failed to handle key=g. Illegal value for `line`

### ISSUE THREAD

**Issue by Bavon101** [VSCodeVim/Vim#5869]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=g. Illegal value for `line`
	at d._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
	at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
	at le (/Users/isaacmoovn/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:206217)
	at n.execActionWithCount (/Users/isaacmoovn/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:206753)
	at F.executeMovement (/Users/isaacmoovn/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:175649)
	at F.runAction (/Users/isaacmoovn/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171527)
	at F.handleKeyAsAnAction (/Users/isaacmoovn/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170985)
	at F.handleKeyEvent (/Users/isaacmoovn/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167823)
	at Object.promise (/Users/isaacmoovn/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216277)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/Users/isaacmoovn/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by Bavon101** [comment]
I was just opening the VS code as always, then the error pipes up

{✓}
