### ISSUE TITLE
Failed to handle key=l. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by glenn1976** [VSCodeVim/Vim#5922]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=l. Illegal argument: line must be non-negative
    at Object.t.illegalArgument (/private/var/folders/3v/7jj3h1vj1cn20z82tm3hvhb00000gq/T/AppTranslocation/2819D75D-2A74-46AA-A2E8-43E2A9DEFB13/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:11:10)
    at new y (/private/var/folders/3v/7jj3h1vj1cn20z82tm3hvhb00000gq/T/AppTranslocation/2819D75D-2A74-46AA-A2E8-43E2A9DEFB13/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:534:364)
    at new y (/private/var/folders/3v/7jj3h1vj1cn20z82tm3hvhb00000gq/T/AppTranslocation/2819D75D-2A74-46AA-A2E8-43E2A9DEFB13/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:531:904)
    at t.u.Position.add (/Users/glennverosil 1/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:64402)
    at /Users/glennverosil 1/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:69277
    at Array.reduce (<anonymous>)
    at /Users/glennverosil 1/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:69243
    at Array.map (<anonymous>)
    at v.execute (/Users/glennverosil 1/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:69092)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.executeOperator (/Users/glennverosil 1/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:177681)
    at F.runAction (/Users/glennverosil 1/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:172320)
    at F.handleKeyAsAnAction (/Users/glennverosil 1/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
    at F.handleKeyEvent (/Users/glennverosil 1/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
    at Object.promise (/Users/glennverosil 1/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
    at Object.runTasks (/Users/glennverosil 1/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment]
Was fixed a few months ago, please upgrade if you haven't already
