### ISSUE TITLE
Failed to handle key=p. Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by dreamtraveler** [VSCodeVim/Vim#5944]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. Cannot read property 'split' of undefined
	at n.exec (/Users/lei.tan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:103192)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async w.exec (/Users/lei.tan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:107038)
	at async w.execCount (/Users/lei.tan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:24641)
	at async F.runAction (/Users/lei.tan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171581)
	at async F.handleKeyAsAnAction (/Users/lei.tan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/Users/lei.tan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/Users/lei.tan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (/Users/lei.tan/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by sql-koala** [comment]
set #5934 
:D
