### ISSUE TITLE
Failed to handle key=s. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by premwit555** [VSCodeVim/Vim#5982]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=s. Illegal argument: line must be non-negative
    at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:11:10)
    at new y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:534:364)
    at new y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:531:904)
    at t.u.Position.add (/Users/m1n/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:1:64402)
    at /Users/m1n/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:69277
    at Array.reduce (<anonymous>)
    at /Users/m1n/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:69243
    at Array.map (<anonymous>)
    at v.execute (/Users/m1n/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:69092)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at F.runAction (/Users/m1n/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:171647)
    at F.handleKeyAsAnAction (/Users/m1n/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
    at F.handleKeyEvent (/Users/m1n/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
    at Object.promise (/Users/m1n/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
    at Object.runTasks (/Users/m1n/.vscode/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment]
Was fixed a few months ago, please upgrade if you haven't already
