### ISSUE TITLE
Failed to handle key=<C-v>. command '" p' not found

### ISSUE THREAD

**Issue by kornatskyi** [VSCodeVim/Vim#6061]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: command '" p' not found
    at u._tryExecuteCommand (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4189:893)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4189:774
```

</details>

**Comment by kornatskyi** [comment]
Sorry, send it accidentally.
