### ISSUE TITLE
The :normal command does not support keybindings

### ISSUE THREAD

**Issue by lsDrizzle** [VSCodeVim/Vim#6073]
**Describe the bug**
I bind `jkil` to `hjkl`, respectively, in the normal mode, in order to use `i` as `<up>`. I also bind `h` to `i` and `H` to `I`. It works well in the normal mode, that is, I can use `H` to insert at the beginning of the line. However, these keybindings do not work when I use the `:norm` command. 

**To Reproduce**
1. Install neovim and set
```
    "vim.enableNeovim": true,
    "vim.neovimPath": "/usr/local/bin/nvim"
```
2.  Bind `H` to `I` using
```
"vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "H",
            ],
            "after": [
                "I",
            ]
        },
],
```
3.  Type `V` to select a line
4.  Type `:norm Ha`, then type `<CR>` to execute it.
5.  You will see that Vim returns to the normal mode. Nothing else happens.

**Expected behavior**
Since I bind `H` to `I`, I hope to insert a char `a` at the beginning of the selected line by using `:norm Ha`.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.
This is the log output when I did the Step 2~4 above.
```
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=V. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys=V. mode=Normal. keybindings=normalModeKeyBindingsMap. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: verbose: key=V. keySlice=V. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: Selections: Adding Selection Change to be Ignored! Hash: [22, 0; 22, 34], Selections: [22, 0], [22, 34] (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] vscode-context: debug: Setting key='vim.mode' to value='VisualLine' (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Extension Startup: debug: Selections: Ignoring selection: [22, 0; 22, 34], Count left: 0 (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent('V') took 12ms (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=:. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys=:. mode=VisualLine. keybindings=visualModeKeyBindingsMap. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: verbose: key=:. keySlice=:. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] vscode-context: debug: Setting key='vim.mode' to value='CommandlineInProgress' (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent(':') took 15ms (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=n. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys=n. mode=CommandlineInProgress. keybindings=commandLineModeKeyBindingsMap. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent('n') took 1ms (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=o. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys=o. mode=CommandlineInProgress. keybindings=commandLineModeKeyBindingsMap. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent('o') took 2ms (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=r. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys=r. mode=CommandlineInProgress. keybindings=commandLineModeKeyBindingsMap. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent('r') took 1ms (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=m. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys=m. mode=CommandlineInProgress. keybindings=commandLineModeKeyBindingsMap. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent('m') took 2ms (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=<space>. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys= . mode=CommandlineInProgress. keybindings=commandLineModeKeyBindingsMap. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent('<space>') took 1ms (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=H. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys=H. mode=CommandlineInProgress. keybindings=commandLineModeKeyBindingsMap. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent('H') took 2ms (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=a. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys=a. mode=CommandlineInProgress. keybindings=commandLineModeKeyBindingsMap. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent('a') took 1ms (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=<enter>. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys=. mode=CommandlineInProgress. keybindings=commandLineModeKeyBindingsMap. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Extension Startup: debug: Selections: ignoring intermediate selection change: [22, 0; 22, 28] (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Neovim: debug: Running :'<lt>,'>norm Ha. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Neovim: debug: 30 lines in nvim. 30 in editor. (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Extension Startup: debug: Selections: ignoring intermediate selection change: [6, 2; 6, 2] (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Extension Startup: debug: Selections: ignoring intermediate selection change: [6, 5; 6, 5] (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: Selections: Adding Selection Change to be Ignored! Hash: [22, 21; 22, 21], Selections: [22, 21], [22, 21] (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] vscode-context: debug: Setting key='vim.mode' to value='Normal' (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] Extension Startup: debug: Selections: Ignoring selection: [22, 21; 22, 21], Count left: 0 (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent('<enter>') took 102ms (at t.ConsoleForElectron.log (/Users/drizzle/.vscode-insiders/extensions/vscodevim.vim-1.18.5/out/extension.js:11:17938))
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.18.5
- VSCode version: 1.53.0-insider
- OS: Mac OS 11.1 (Big Sur)

**Comment by lsDrizzle** [comment]
Note that I have also bound `H` to `I` in "vim.visualModeKeyBindingsNonRecursive" and "vim.operatorPendingModeKeyBindingsNonRecursive", but the bug still remains.

**Comment by sql-koala** [comment]
Hi, @J-Fields , @lsDrizzle 
I don't think this is a bug. How can neovim know about the keybindings in vscodevim config?

@lsDrizzle 
Look at this:
https://github.com/VSCodeVim/Vim/blob/master/README.md#vimrc-support
You could create a small vimrc file for simple mappings, that you want to share between neovim and vscodevim.
If you want neovim just as backend for vscodevim, you still need to give it the mappings in a simple vimrc file:
`nnoremap H I`

**Comment by lsDrizzle** [comment]
> Hi, @J-Fields , @lsDrizzle
> I don't think this is a bug. How can neovim know about the keybindings in vscodevim config?
> 
> @lsDrizzle
> Look at this:
> https://github.com/VSCodeVim/Vim/blob/master/README.md#vimrc-support
> You could create a small vimrc file for simple mappings, that you want to share between neovim and vscodevim.
> If you want neovim just as backend for vscodevim, you still need to give it the mappings in a simple vimrc file:
> `nnoremap H I`

Hi @sql-koala , thanks a lot for the reply.
Actually, I have also tried to set the mapping in `init.vim`, and have used `"vim.vimrc.enable": true` and `"vim.vimrc.path": "~/.config/nvim/init.vim"` according to the instructions you mentioned.   
It turns out that while the mapping `nnoremap H I` works in the normal mode, the `:normal Ha` command still doesn't work.

One more thing, in fact I am also a little confused about why `:normal` is a neovim feature. As far as I know, vim (at least in vim 8.2) also supports it. To demonstrate this, just type `: help normal` in vim 8.2.

**Comment by sql-koala** [comment]
@lsDrizzle Yes, ":normal" is from regular vim.
We as vscodevim use neovim to handle/process many commandline commands (because we can't reimplement it all). I am no expert on this.
But the way you tried it with init.vim, I would expect to work.

**Comment by J-Fields** [comment]
We don't currently load neovim with any config - #5071 should fix this, I think

**Comment by lsDrizzle** [comment]
Yeah, I took a look at #5071 and it should be what I need. Thanks for the reminder! Hope the feature could be added soon.
