### ISSUE TITLE
Failed to handle key=j. [vscodevim.vim]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscodevim.vim

### ISSUE THREAD

**Issue by AlfredMan** [VSCodeVim/Vim#6097]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.8

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=j. [vscodevim.vim]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscodevim.vim
	at a (/private/var/folders/3v/xryfwy3s4c30krpzs2ckkvl00000gn/T/AppTranslocation/B8649C65-C649-4FB2-A0D0-9D371E7299AC/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:509:620)
	at Object.t.checkProposedApiEnabled (/private/var/folders/3v/xryfwy3s4c30krpzs2ckkvl00000gn/T/AppTranslocation/B8649C65-C649-4FB2-A0D0-9D371E7299AC/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:509:982)
	at x.getConfiguration (/private/var/folders/3v/xryfwy3s4c30krpzs2ckkvl00000gn/T/AppTranslocation/B8649C65-C649-4FB2-A0D0-9D371E7299AC/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:699:923)
	at Object.getConfiguration (/private/var/folders/3v/xryfwy3s4c30krpzs2ckkvl00000gn/T/AppTranslocation/B8649C65-C649-4FB2-A0D0-9D371E7299AC/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:791:3)
	at f.getConfiguration (/Users/alfred/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:646094)
	at f.get [as editorCursorStyleRaw] (/Users/alfred/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:646938)
	at f.get editorCursorStyle [as editorCursorStyle] (/Users/alfred/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:646460)
	at F.updateView (/Users/alfred/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:718873)
	at F.handleKeyAsAnAction (/Users/alfred/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:707246)
	at async F.handleKeyEvent (/Users/alfred/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:703983)
	at async Object.promise (/Users/alfred/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:350696)
	at async Object.runTasks (/Users/alfred/.vscode/extensions/vscodevim.vim-1.18.8/out/extension.js:2:754478)
```

</details>

**Comment by J-Fields** [comment]
What version of VSCode are you running?

**Comment by J-Fields** [comment]
Closing as not enough info provided
