### ISSUE TITLE
Failed to handle key=. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by lrvideckis** [VSCodeVim/Vim#6115]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=
. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:680269)
	at h.setLastHistoryEndPosition (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:687891)
	at F.runAction (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:711089)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/lrvideckis/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
Fixed on master
