### ISSUE TITLE
Failed to handle key=p. Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Isaac-chip** [VSCodeVim/Vim#6136]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. Cannot read property 'split' of undefined
    at n.exec (/Users/isaac-chip/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:472941)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at w.exec (/Users/isaac-chip/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:476787)
    at w.execCount (/Users/isaac-chip/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:355705)
    at F.runAction (/Users/isaac-chip/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707788)
    at F.handleKeyAsAnAction (/Users/isaac-chip/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
    at F.handleKeyEvent (/Users/isaac-chip/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
    at Object.promise (/Users/isaac-chip/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
    at Object.runTasks (/Users/isaac-chip/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by Isaac-chip** [comment]
using vim plugin will  throw error.click on command + d select more than two wrods.
