### ISSUE TITLE
Failed to handle key=<Esc>. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by KPMGE** [VSCodeVim/Vim#6146]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. HistoryTracker:Tried to modify history at index -1
    at h.get currentHistoryStep [as currentHistoryStep] (/home/kevin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:680269)
    at h._isDocumentTextNeeded (/home/kevin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:683272)
    at h.addChange (/home/kevin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:683465)
    at F.handleKeyAsAnAction (/home/kevin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:705657)
    at F.handleKeyEvent (/home/kevin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704026)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.promise (/home/kevin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)
    at Object.runTasks (/home/kevin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
Fixed on master, will be in next release
