### ISSUE TITLE
Failed to handle key=j. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by fb-bob-ren** [VSCodeVim/Vim#6163]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=j. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/bobren/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:200309)
	at h._isDocumentTextNeeded (/Users/bobren/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:203302)
	at h.addChange (/Users/bobren/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:203495)
	at F.handleKeyAsAnAction (/Users/bobren/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:169454)
	at F.handleKeyEvent (/Users/bobren/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167823)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/bobren/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:9:216269)
	at async Object.runTasks (/Users/bobren/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment]
Fixed on master, will be in next release (also, please upgrade to latest version 🙂)

**Comment by fb-bob-ren** [comment]
Thanks just updated. One sad thing is my vim settings got wiped. Had to manually reset the leader key on update.

**Comment by J-Fields** [comment]
Sorry about that, not sure why that happened
