### ISSUE TITLE
HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by brianpilati** [VSCodeVim/Vim#6170]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/brian.pilati/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:680269)
	at h.getMarks (/Users/brian.pilati/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:683004)
	at F.updateView (/Users/brian.pilati/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:720837)
	at M (/Users/brian.pilati/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:344960)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.promise (/Users/brian.pilati/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350640)
	at async Object.runTasks (/Users/brian.pilati/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in latest release
