### ISSUE TITLE
Failed to handle key=d. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by jinho10** [VSCodeVim/Vim#6173]
**To Reproduce**

1.  Go to do an edit file
2.  Reverse using the key 'u' multiple times
3.  Then it ends up unable to reverse and pop up the error 

This happens all the time for some reason in my vscode. I am using company-built vscode (FB). I have not located any issues with other tools. 

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=d. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:680269)
	at h._addNewHistoryStep (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:681125)
	at h.addChange (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:683835)
	at F.runAction (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:709964)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

other keys same at this point

```
Error: Failed to handle key=u. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:680269)
	at h._isDocumentTextNeeded (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:683272)
	at h.addChange (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:683465)
	at F.handleKeyAsAnAction (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:705657)
	at F.handleKeyEvent (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704026)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/jinhohwang/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
This SHOULD be fixed on master. Once 1.19.0 is released, please let me know if you see this again.
