### ISSUE TITLE
Failed to handle key=h. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by jimmy-peng** [VSCodeVim/Vim#6175]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=h. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\Administrator\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:680269)
	at h._isDocumentTextNeeded (c:\Users\Administrator\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:683272)
	at h.addChange (c:\Users\Administrator\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:683465)
	at F.handleKeyAsAnAction (c:\Users\Administrator\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:705657)
	at F.handleKeyEvent (c:\Users\Administrator\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:704026)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.promise (c:\Users\Administrator\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:350696)
	at async Object.runTasks (c:\Users\Administrator\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in the next version, let me know if you still experience this.
