### ISSUE TITLE
Failed to handle key=a. Cannot read property 'getFocusElement' of null

### ISSUE THREAD

**Issue by jeanlucthumm** [VSCodeVim/Vim#6187]
**To Reproduce**

Include the following in `settings.json`:
```
    "vim.leader": "<space>",
    "vim.normalModeKeyBindings": [
        {
            "before": [
                "<leader>",
                "a"
            ],
            "commands": [
                "problems.action.showQuickFixes"
            ]
        }
    ]
```
Then go to a problem in the code. Attempt to do `<space>a` to bring up quickfix, and the given problem occurs. In the same position if you hit Ctr + period key, it brings up the quickfix menu.

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'getFocusElement' of null
    at handler (file:///usr/share/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:2555:1426)
    at C.invokeFunction (file:///usr/share/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:614:20943)
    at C._tryExecuteCommand (file:///usr/share/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:1534:3492)
    at file:///usr/share/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:1534:3241
```

</details>

**Comment by J-Fields** [comment]
Weird. I can reproduce, but this exception is being thrown from VSCode. Not sure what's going wrong here, I'll need to dig into it a bit more.

**Comment by ds300** [comment]
i solved this problem by using `editor.action.quickFix` instead
