### ISSUE TITLE
Failed to handle key=k. HistoryTracker:Tried to modify history at index -1 (the vim plugin is totally unusable due to this issue as undo has ~30% chances of hitting this error)

### ISSUE THREAD

**Issue by undefinedbehavior** [VSCodeVim/Vim#6203]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=k. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/yirui/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:680269)
	at h.setLastHistoryEndPosition (/Users/yirui/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:687891)
	at F.runAction (/Users/yirui/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:711089)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/yirui/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/yirui/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/yirui/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/yirui/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by undefinedbehavior** [comment]
Let me know if there's anything I can help to provide more repro steps or info.

The bug happens 1/3 of the time when I perform undo via key `u`.
On top of this issue, undo also most times couldn't undo for more than 2 or 3 times even I made lots of changes. 
All functionality was working just fine 2 months ago.

**Comment by J-Fields** [comment]
This should be fixed in the upcoming version, sorry for the inconvenience.
