### ISSUE TITLE
Failed to handle key=<C-a>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by GTOnizuka13** [VSCodeVim/Vim#6207]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal argument: character must be non-negative
	at Object.t.illegalArgument (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:11:10)
	at new y (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:534:424)
	at new y (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:531:904)
	at a (/home/elijiah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360191)
	at F.exec (/home/elijiah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:360236)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async S.exec (/home/elijiah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:460560)
	at async S.execCount (/home/elijiah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:355705)
	at async F.runAction (/home/elijiah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707788)
	at async F.handleKeyAsAnAction (/home/elijiah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/home/elijiah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/home/elijiah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:346362)
	at async Object.runTasks (/home/elijiah/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
Closing as duplicate of #6339
