### ISSUE TITLE
Failed to handle key=u. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by ameeruljunaidi** [VSCodeVim/Vim#6225]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=u. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:680269)
	at h.goBackHistoryStep (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:685405)
	at je.exec (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:384070)
	at je.execCount (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:355251)
	at F.runAction (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:707796)
	at F.handleKeyAsAnAction (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:707190)
	at F.handleKeyEvent (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:704026)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.promise (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:350696)
	at async Object.runTasks (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
This will be fixed in the next release
