### ISSUE TITLE
HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by ameeruljunaidi** [VSCodeVim/Vim#6226]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:680269)
	at h.getMarks (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:683004)
	at F.updateView (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:720837)
	at M (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:344960)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.promise (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:349203)
	at async Object.runTasks (c:\Users\ameer\.vscode-insiders\extensions\vscodevim.vim-1.18.9\out\extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
This will be fixed in the next release
