### ISSUE TITLE
HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by olliegilbey** [VSCodeVim/Vim#6228]
**To Reproduce**

1.  During a Live Share session where I was a participant (not the host)
2.  Make a normal CMD+F find and replace
3.  Press 'u' to undo
4.  Operation lags heavily
5.  Starts to error with the below every time the host makes a change.

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/ogilbey/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:680269)
	at h.getMarks (/Users/ogilbey/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:683004)
	at F.updateView (/Users/ogilbey/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:720837)
	at M (/Users/ogilbey/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:344960)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.promise (/Users/ogilbey/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:349203)
	at async Object.runTasks (/Users/ogilbey/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
This will be fixed in next release
