### ISSUE TITLE
Failed to handle key=%. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by sacckth** [VSCodeVim/Vim#6249]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=%. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\schavezc\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:680269)
	at h.setLastHistoryEndPosition (c:\Users\schavezc\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:687891)
	at F.runAction (c:\Users\schavezc\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:711089)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async F.handleKeyAsAnAction (c:\Users\schavezc\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:707179)
	at async F.handleKeyEvent (c:\Users\schavezc\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:704015)
	at async Object.promise (c:\Users\schavezc\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:350696)
	at async Object.runTasks (c:\Users\schavezc\.vscode\extensions\vscodevim.vim-1.18.9\out\extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
Will be fixed in next release
