### ISSUE TITLE
Failed to handle key= . Running the contributed command: 'vspacecode.space' failed.

### ISSUE THREAD

**Issue by arnavsharma93** [VSCodeVim/Vim#6268]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key= . Running the contributed command: 'vspacecode.space' failed.
	at S._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:103934)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async m.handleRemapping (/Users/aarnav/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:660145)
	at async m.sendKey (/Users/aarnav/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:658035)
	at async t.Remappers.sendKey (/Users/aarnav/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:654443)
	at async F.handleKeyEvent (/Users/aarnav/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:703683)
	at async Object.promise (/Users/aarnav/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/aarnav/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
Do you have vspacecode installed?

**Comment by arnavsharma93** [comment]
Yes, indeed. I was facing this quite frequently on the stable VS Code build. I switched to VS Code Insiders, and it's been working rather well since then.

**Comment by J-Fields** [comment]
Hmm, strange. Can you open an issue in that repo instead? I don't think this is VSCodeVim's fault
