### ISSUE TITLE
HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by SuperCope** [VSCodeVim/Vim#6281]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: HistoryTracker:Tried to modify history at index -1
    at h.get currentHistoryStep [as currentHistoryStep] (/home/robin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:680269)
    at h.getMarks (/home/robin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:683004)
    at F.updateView (/home/robin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:720837)
    at F.handleSelectionChange (/home/robin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:700636)
    at Object.promise (/home/robin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350380)
    at Object.runTasks (/home/robin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754585)
    at Object.enqueueTask (/home/robin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:755624)
    at /home/robin/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350361
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in upcoming release
