### ISSUE TITLE
Failed to handle key=<Esc>. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by mvcccccc** [VSCodeVim/Vim#6294]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/mavc/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:200309)
	at h._isDocumentTextNeeded (/Users/mavc/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:203302)
	at h.addChange (/Users/mavc/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:203495)
	at F.handleKeyAsAnAction (/Users/mavc/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:169454)
	at F.handleKeyEvent (/Users/mavc/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167823)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/mavc/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:9:211972)
	at async Object.runTasks (/Users/mavc/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment]
Should be fixed on next release
