### ISSUE TITLE
Failed to handle key=4. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by lurunming** [VSCodeVim/Vim#6302]
**To Reproduce**

1.  type something
2.  execute several 'dd' command
3.  execute 'u's
4.  execute 'j' and see the error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=4. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/runming/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:680269)
	at h.setLastHistoryEndPosition (/Users/runming/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:687891)
	at F.runAction (/Users/runming/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:711089)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/runming/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/runming/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/runming/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/runming/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in latest release
