### ISSUE TITLE
Failed to handle key=<right>. Cannot read property 'isOperator' of undefined

### ISSUE THREAD

**Issue by karimk123** [VSCodeVim/Vim#6309]
**To Reproduce**

1.press ctrl+x in insert mode
2. move with arrow keys

**VSCodeVim version**: 1.19.0

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<right>. Cannot read property 'isOperator' of undefined
    at filter (c:\Users\karim\.vscode\extensions\vscodevim.vim-1.19.0\src\state\recordedState.ts:220:64)
    at Array.filter (<anonymous>)
    at a.operators (c:\Users\karim\.vscode\extensions\vscodevim.vim-1.19.0\src\state\recordedState.ts:220:28)
    at a.operator (c:\Users\karim\.vscode\extensions\vscodevim.vim-1.19.0\src\state\recordedState.ts:215:28)
    at I.executeMovement (c:\Users\karim\.vscode\extensions\vscodevim.vim-1.19.0\src\mode\modeHandler.ts:956:77)
    at runMicrotasks (<anonymous>)
    at process.recordedState (internal/process/task_queues.js:97:5)
    at I.actionToRecord [as runAction] (c:\Users\karim\.vscode\extensions\vscodevim.vim-1.19.0\src\mode\modeHandler.ts:700:7)
    at I.handledAsAction [as handleKeyAsAnAction] (c:\Users\karim\.vscode\extensions\vscodevim.vim-1.19.0\src\mode\modeHandler.ts:643:43)
    at I.async [as handleKeyEvent] (c:\Users\karim\.vscode\extensions\vscodevim.vim-1.19.0\src\mode\modeHandler.ts:469:11)
    at Object.promise (c:\Users\karim\.vscode\extensions\vscodevim.vim-1.19.0\extensionBase.ts:632:27)
    at Object.runTasks (c:\Users\karim\.vscode\extensions\vscodevim.vim-1.19.0\src\taskQueue.ts:36:26)
```

</details>

**Comment by vj11100** [comment]
Is there a solution for this bug?

**Comment by J-Fields** [comment]
Yeah, update to 1.19.1
