### ISSUE TITLE
Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined

### ISSUE THREAD

**Issue by JaimeMiguelHernandez** [VSCodeVim/Vim#6343]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=<Esc>. Cannot read property 'previousMode' of undefined
    at I.updateView (/home/jaime_m_h/.vscode/extensions/vscodevim.vim-1.19.1/src/mode/modeHandler.ts:1171:50)
    at I.handleKeyAsAnAction (/home/jaime_m_h/.vscode/extensions/vscodevim.vim-1.19.1/src/mode/modeHandler.ts:657:16)
    at process.handledAsAction (internal/process/task_queues.js:97:5)
    at I.async [as handleKeyEvent] (/home/jaime_m_h/.vscode/extensions/vscodevim.vim-1.19.1/src/mode/modeHandler.ts:469:11)
    at Object.promise (/home/jaime_m_h/.vscode/extensions/vscodevim.vim-1.19.1/extensionBase.ts:632:27)
    at Object.runTasks (/home/jaime_m_h/.vscode/extensions/vscodevim.vim-1.19.1/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment]
Any chance you can reproduce (or know what you were doing when this happened?

**Comment by JaimeMiguelHernandez** [comment]
Sorry for the inconvenience. After closing and opening everything was again fine.

**Comment by J-Fields** [comment]
No worries. Re-opening as these sorts of issues are often transient, and the stack trace is helpful.
