### ISSUE TITLE
Cannot read property 'isOperator' of undefined

### ISSUE THREAD

**Issue by yacouba55** [VSCodeVim/Vim#6344]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.0

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'isOperator' of undefined
    at /home/dark/.vscode/extensions/vscodevim.vim-1.19.0/out/extension.js:2:779767
    at Array.filter (<anonymous>)
    at a.get operators [as operators] (/home/dark/.vscode/extensions/vscodevim.vim-1.19.0/out/extension.js:2:779754)
    at a.get operator [as operator] (/home/dark/.vscode/extensions/vscodevim.vim-1.19.0/out/extension.js:2:779675)
    at a.isOperatorPending (/home/dark/.vscode/extensions/vscodevim.vim-1.19.0/out/extension.js:2:780484)
    at m.get currentModeIncludingPseudoModes [as currentModeIncludingPseudoModes] (/home/dark/.vscode/extensions/vscodevim.vim-1.19.0/out/extension.js:2:788363)
    at I.updateView (/home/dark/.vscode/extensions/vscodevim.vim-1.19.0/out/extension.js:2:756184)
    at _ (/home/dark/.vscode/extensions/vscodevim.vim-1.19.0/out/extension.js:2:377699)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.promise (/home/dark/.vscode/extensions/vscodevim.vim-1.19.0/out/extension.js:2:383601)
    at Object.runTasks (/home/dark/.vscode/extensions/vscodevim.vim-1.19.0/out/extension.js:2:794795)
```

</details>

**Comment by J-Fields** [comment]
This was fixed in 1.19.1
