### ISSUE TITLE
Cannot read property 'isOperator' of undefined

### ISSUE THREAD

**Issue by Nillkizz** [VSCodeVim/Vim#6355]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.0

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'isOperator' of undefined
    at filter (/home/nillkizz/.vscode-oss/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:220:64)
    at Array.filter (<anonymous>)
    at a.operators (/home/nillkizz/.vscode-oss/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:220:28)
    at a.operator (/home/nillkizz/.vscode-oss/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:215:28)
    at a.isOperatorPending (/home/nillkizz/.vscode-oss/extensions/vscodevim.vim-1.19.0/src/state/recordedState.ts:287:12)
    at m.currentModeIncludingPseudoModes (/home/nillkizz/.vscode-oss/extensions/vscodevim.vim-1.19.0/src/state/vimState.ts:252:31)
    at I.handleKeyEvent (/home/nillkizz/.vscode-oss/extensions/vscodevim.vim-1.19.0/src/mode/modeHandler.ts:424:39)
    at Object.promise (/home/nillkizz/.vscode-oss/extensions/vscodevim.vim-1.19.0/extensionBase.ts:633:16)
    at Object.runTasks (/home/nillkizz/.vscode-oss/extensions/vscodevim.vim-1.19.0/src/taskQueue.ts:37:20)
    at Object.enqueueTask (/home/nillkizz/.vscode-oss/extensions/vscodevim.vim-1.19.0/src/taskQueue.ts:108:12)
    at T (/home/nillkizz/.vscode-oss/extensions/vscodevim.vim-1.19.0/extensionBase.ts:632:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

</details>

**Comment by Nillkizz** [comment]
Just in work time...

**Comment by J-Fields** [comment]
This has been fixed, please upgrade to the latest version.
