### ISSUE TITLE
Failed to handle key=s. Illegal value for `line`

### ISSUE THREAD

**Issue by longtran2020** [VSCodeVim/Vim#6365]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=s. Illegal value for `line`
	at d._lineAt (/private/var/folders/ny/n951t8492vz_7tk24zyk22_00000gn/T/AppTranslocation/354A0E65-8F87-47E1-8E5A-766B74C55D5E/d/Visual Studio Code-1.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:571:740)
	at Object.lineAt (/private/var/folders/ny/n951t8492vz_7tk24zyk22_00000gn/T/AppTranslocation/354A0E65-8F87-47E1-8E5A-766B74C55D5E/d/Visual Studio Code-1.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:570:715)
	at C.run (/Users/paveltran/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:521665)
	at N.run (/Users/paveltran/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:528946)
	at k.run (/Users/paveltran/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:523906)
	at F.executeOperator (/Users/paveltran/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:713529)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.runAction (/Users/paveltran/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:708540)
	at async F.handleKeyAsAnAction (/Users/paveltran/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/paveltran/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/paveltran/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/paveltran/.vscode/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by J-Fields** [comment]
Please upgrade to the latest version
