### ISSUE TITLE
Failed to handle key=<BS>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by TunchinKao** [VSCodeVim/Vim#6383]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Overlapping ranges are not allowed!
    at T._applyEdit (c:\Users\tunch\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:51884)
    at Object.edit (c:\Users\tunch\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:49576)
    at Object.executeTransformations (c:\Users\tunch\.vscode\extensions\vscodevim.vim-1.19.3\src\transformations\execute.ts:122:29)
    at I.runAction (c:\Users\tunch\.vscode\extensions\vscodevim.vim-1.19.3\src\mode\modeHandler.ts:722:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at I.handledAsAction [as handleKeyAsAnAction] (c:\Users\tunch\.vscode\extensions\vscodevim.vim-1.19.3\src\mode\modeHandler.ts:647:43)
    at I.async [as handleKeyEvent] (c:\Users\tunch\.vscode\extensions\vscodevim.vim-1.19.3\src\mode\modeHandler.ts:469:11)
    at Object.promise (c:\Users\tunch\.vscode\extensions\vscodevim.vim-1.19.3\extensionBase.ts:632:27)
    at Object.runTasks (c:\Users\tunch\.vscode\extensions\vscodevim.vim-1.19.3\src\taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment]
What were you trying to do when this happened? Can you reproduce?

**Comment by TunchinKao** [comment]
Sorry. Latter on, I found it's probably my taiwanese entering causes this error. If it happens again I will try to reproduce it.
Thanks for your comment
