### ISSUE TITLE
Failed to handle key=<BS>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by styx** [VSCodeVim/Vim#6471]
**To Reproduce**

1.  Unfortunately I don't know

**VSCodeVim version**: 1.19.3

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Overlapping ranges are not allowed!
    at R._applyEdit (/snap/code-insiders/681/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:53089)
    at Object.edit (/snap/code-insiders/681/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:50761)
    at Object.executeTransformations (/home/styx/.vscode-insiders/extensions/vscodevim.vim-1.19.3/src/transformations/execute.ts:122:29)
    at I.runAction (/home/styx/.vscode-insiders/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:722:13)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at I.handledAsAction [as handleKeyAsAnAction] (/home/styx/.vscode-insiders/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:647:43)
    at I.async [as handleKeyEvent] (/home/styx/.vscode-insiders/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:469:11)
    at Object.promise (/home/styx/.vscode-insiders/extensions/vscodevim.vim-1.19.3/extensionBase.ts:632:27)
    at Object.runTasks (/home/styx/.vscode-insiders/extensions/vscodevim.vim-1.19.3/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment]
Duplicate of #5224 (I think)
