### ISSUE TITLE
Error while installing 'Vim' extension (VSCodium) Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by eltenedor** [VSCodeVim/Vim#6506]
**Describe the bug**
I cannot install the Vim extension through VS Marketplace. I get the error 

```Corrupt ZIP: end of central directory record signature not found. See below for the complete error log```

**Error Log**
```
[2021-04-20 08:11:09.702] [renderer1] [error] Cannot read property 'resource' of undefined: TypeError: Cannot read property 'resource' of undefined
	at c.deserializeWebviewPanel (/usr/share/codium/resources/app/extensions/markdown-language-features/dist/extension.js:1:107414)
	at o.$deserializeWebviewPanel (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:65833)
	at c._doInvokeHandler (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12794)
	at c._invokeHandler (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12478)
	at c._receiveRequest (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11145)
	at c._receiveOneMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:9931)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:8032
	at _.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at E.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:30083
	at _.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at E.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
	at t._receiveMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20754)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17640
	at _.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at acceptChunk (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12861)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12209
	at Socket.w (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:13173)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
[2021-04-20 08:12:47.390] [renderer1] [error] ["validating: Corrupt ZIP: end of central directory record signature not found","    at H.downloadInstallableExtension (file:///usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217827)","    at async H.doInstallFromGallery (file:///usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214968)"]
[2021-04-20 08:12:47.391] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at H.downloadInstallableExtension (file:///usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217827)
    at async H.doInstallFromGallery (file:///usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214968)
```
**Environment (please complete the following information):**

VSCodium: 1.55.2
OS: Ubuntu Linux (20.10)

![image](https://user-images.githubusercontent.com/3385756/115346606-ac2edb00-a1b0-11eb-8858-d31d6bf73899.png)

vscodevim v1.19.3 or v1.20.0? Screenshot contains both versions
![image](https://user-images.githubusercontent.com/3385756/115346739-dbdde300-a1b0-11eb-8b11-2d4bd2b62fd6.png)

**Comment by J-Fields** [comment]
Can you file an issue with vscode? I have no idea what's going on here but I'd be surprised if it's the extension's fault
