### ISSUE TITLE
Failed to handle key=<C-d>. Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by mxnrenato** [VSCodeVim/Vim#6515]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.20.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-d>. Illegal argument: character must be non-negative
    at k (c:\Users\RIVERA\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1232)
    at new S (c:\Users\RIVERA\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:75:11816)
    at new S (c:\Users\RIVERA\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:75:11163)
    at $.with (c:\Users\RIVERA\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:75:13449)
    at T.exec (c:\Users\RIVERA\.vscode\extensions\vscodevim.vim-1.20.0\src\actions\commands\insert.ts:486:37)
    at runMicrotasks (<anonymous>)
    at process.j (internal/process/task_queues.js:97:5)
    at T.execCount (c:\Users\RIVERA\.vscode\extensions\vscodevim.vim-1.20.0\src\actions\base.ts:248:42)
    at I.actionToRecord [as runAction] (c:\Users\RIVERA\.vscode\extensions\vscodevim.vim-1.20.0\src\mode\modeHandler.ts:722:40)
    at I.handledAsAction [as handleKeyAsAnAction] (c:\Users\RIVERA\.vscode\extensions\vscodevim.vim-1.20.0\src\mode\modeHandler.ts:651:43)
    at I.async [as handleKeyEvent] (c:\Users\RIVERA\.vscode\extensions\vscodevim.vim-1.20.0\src\mode\modeHandler.ts:471:11)
    at Object.promise (c:\Users\RIVERA\.vscode\extensions\vscodevim.vim-1.20.0\extensionBase.ts:628:27)
    at Object.runTasks (c:\Users\RIVERA\.vscode\extensions\vscodevim.vim-1.20.0\src\taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment]
Should've been fixed by 80dae08a5ff994ca5e5d27fe88a64ee4f028cbd7 - will be included in next release
