### ISSUE TITLE
Failed to handle key=<C-a>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by binary-tanya** [VSCodeVim/Vim#6532]
**VSCodeVim version**: 1.20.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Overlapping ranges are not allowed!
    at T._applyEdit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:51884)
    at Object.edit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:49576)
    at Object.executeTransformations (/home/tanya/.vscode/extensions/vscodevim.vim-1.20.0/src/transformations/execute.ts:124:29)
    at I.runAction (/home/tanya/.vscode/extensions/vscodevim.vim-1.20.0/src/mode/modeHandler.ts:726:13)
    at process.actionToRecord (internal/process/task_queues.js:97:5)
    at I.handledAsAction [as handleKeyAsAnAction] (/home/tanya/.vscode/extensions/vscodevim.vim-1.20.0/src/mode/modeHandler.ts:651:43)
    at I.async [as handleKeyEvent] (/home/tanya/.vscode/extensions/vscodevim.vim-1.20.0/src/mode/modeHandler.ts:471:11)
    at Object.promise (/home/tanya/.vscode/extensions/vscodevim.vim-1.20.0/extensionBase.ts:628:27)
    at Object.runTasks (/home/tanya/.vscode/extensions/vscodevim.vim-1.20.0/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment]
This should be fixed in the next release
