### ISSUE TITLE
Failed to handle key=s. Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by glkappe** [VSCodeVim/Vim#6545]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.3

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=s. Cannot read property 'text' of undefined
    at Function.putMulticursorRegister (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/src/register/register.ts:138:40)
    at Function.put (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/src/register/register.ts:74:18)
    at x.run (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/src/actions/operator.ts:286:14)
    at N.run (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/src/actions/operator.ts:605:51)
    at k.run (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/src/actions/operator.ts:384:32)
    at I.executeOperator (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:1059:24)
    at process.operator (internal/process/task_queues.js:97:5)
    at I.actionToRecord [as runAction] (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:761:11)
    at I.handledAsAction [as handleKeyAsAnAction] (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:647:43)
    at I.keys [as handleKeyEvent] (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:469:11)
    at I.composingText [as handleMultipleKeyEvents] (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/src/mode/modeHandler.ts:366:23)
    at Object.promise (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/extensionBase.ts:434:39)
    at Object.runTasks (/Users/liqihang/.vscode/extensions/vscodevim.vim-1.19.3/src/taskQueue.ts:36:26)
```

</details>

**Comment by J-Fields** [comment]
This should be fixed in 1.20, please upgrade
