### ISSUE TITLE
Failed to handle key=u. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by itissid** [VSCodeVim/Vim#6583]
**To Reproduce**

1.  Go to a file edit it and in normal mode press `u` to undo 
2. See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=u. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:680269)
	at h.setLastHistoryEndPosition (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:687891)
	at F.runAction (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:711089)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:707179)
	at async F.handleKeyEvent (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:704015)
	at async Object.promise (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350696)
	at async Object.runTasks (/Users/itissidharth/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754577)
```

</details>

**Comment by itissid** [comment]
The error does not appear every time I press `u` but after extended editing done in the file.

**Comment by J-Fields** [comment]
This has been fixed, please upgrade
