### ISSUE TITLE
Failed to handle key=j. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by yhcharles** [VSCodeVim/Vim#6609]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=j. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/charlieyan/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:508963)
	at h._isDocumentTextNeeded (/Users/charlieyan/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:511962)
	at h.addChange (/Users/charlieyan/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:512155)
	at F.handleKeyAsAnAction (/Users/charlieyan/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:473282)
	at F.handleKeyEvent (/Users/charlieyan/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:471614)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.promise (/Users/charlieyan/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:235740)
	at async Object.runTasks (/Users/charlieyan/.vscode-fb-mkt/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment]
This has been fixed on a more recent version, please upgrade
