### ISSUE TITLE
HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by jinwilliam-v** [VSCodeVim/Vim#6672]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/songweij/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:680269)
	at h.getMarks (/Users/songweij/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:683004)
	at F.updateView (/Users/songweij/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:720837)
	at F.handleSelectionChange (/Users/songweij/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:700636)
	at Object.promise (/Users/songweij/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350380)
	at Object.runTasks (/Users/songweij/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:754585)
	at Object.enqueueTask (/Users/songweij/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:755624)
	at /Users/songweij/.vscode-fb-mkt/extensions/vscodevim.vim-1.18.9/out/extension.js:2:350361
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

</details>

**Comment by J-Fields** [comment]
Has been fixed, please upgrade
