### ISSUE TITLE
Failed to handle key=<Esc>. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by slaykachu** [VSCodeVim/Vim#6699]
**To Reproduce**
I don't know what I did to get to this state, I seemed trapped in `normal` mode.
Alternating with IDE shortcuts (COMMAND-Z, COMMAND-X), I managed to get back to a working state.

It might related with other history issues (the fact that `u`ndo doesn't work most of the time, I have to use COMMAND-Z instead). 

Thanks! 

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. HistoryTracker:Tried to modify history at index -1
	at h.get currentHistoryStep [as currentHistoryStep] (/Users/ygy/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:200309)
	at h.setLastHistoryEndPosition (/Users/ygy/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:207915)
	at F.runAction (/Users/ygy/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:174898)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async F.handleKeyAsAnAction (/Users/ygy/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:170974)
	at async F.handleKeyEvent (/Users/ygy/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:167812)
	at async Object.promise (/Users/ygy/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:9:211972)
	at async Object.runTasks (/Users/ygy/.vscode-fb-insiders-mkt/extensions/vscodevim.vim-1.18.5/out/extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment]
This has been fixed, please upgrade
