### ISSUE TITLE
getLineLength() called with out-of-bounds line 153

### ISSUE THREAD

**Issue by boweiliu** [VSCodeVim/Vim#6770]
**To Reproduce**

1.  Open a .ts file
2.  Select a chunk of text which includes the last line
3. Right click to Refactor -> Move to a new file
4. VSCode opens the new file. Re-navigate back to the old file
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: getLineLength() called with out-of-bounds line 153
	at Function.getLineLength (/home/bowei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:22225)
	at l.getRight (/home/bowei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:1:10500)
	at F.updateView (/home/bowei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:491590)
	at _ (/home/bowei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:230166)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Object.promise (/home/bowei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234397)
	at async Object.runTasks (/home/bowei/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment]
You're using a very old version - please upgrade
