### ISSUE TITLE
Failed to handle key=<Esc>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by rjayasinghe** [VSCodeVim/Vim#6888]
**To Reproduce**

I fear this might be challenging to reproduce but here is what I did:

1. edit a Java file (with Java extension enabled)
2. enter 2 characters
3. try to trigger auto-completion for Java symbol
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<Esc>. Overlapping ranges are not allowed!
    at n._applyEdit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52275)
    at Object.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:49967)
    at Object.executeTransformations (/Users/i540498/.vscode/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:125:31)
    at j.runAction (/Users/i540498/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (/Users/i540498/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (/Users/i540498/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at /Users/i540498/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:495:53
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Normal"
cursors: [
  "[[27, 6] | [27, 5]]"
]
actionsRunPressedKeys: [
  "i",
  "p",
  "e",
  "<Esc>"
]
actionsRun: [
  "D",
  "Ve",
  "$",
  "C",
  "$",
  "y"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 27,
      "character": 6
    },
    "text": "i",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 27,
        "character": 4
      },
      {
        "line": 27,
        "character": 7
      }
    ],
    "text": "shippedNotificationTriggered",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by convers39** [comment]
any fix for this bug? cannot type anything and have to reload vscode everytime

**Comment by J-Fields** [comment]
@convers39 A fix is coming in the next release
