### ISSUE TITLE
Failed to handle key=<C-a>. Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by 326eunjin** [VSCodeVim/Vim#6916]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<C-a>. Illegal argument: line must be non-negative
    at Object.P [as illegalArgument] (c:\Users\326eu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1232)
    at new b (c:\Users\326eu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:77:15809)
    at new b (c:\Users\326eu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:77:15222)
    at U.with (c:\Users\326eu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:77:17512)
    at $.exec (c:\Users\326eu\.vscode\extensions\vscodevim.vim-1.21.5\src\actions\commands\actions.ts:84:53)
    at $.execCount (c:\Users\326eu\.vscode\extensions\vscodevim.vim-1.21.5\src\actions\base.ts:230:20)
    at j.runAction (c:\Users\326eu\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:724:20)
    at j.rerunRecordedState (c:\Users\326eu\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:1098:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.transformer [as executeTransformations] (c:\Users\326eu\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:207:12)
    at j.actionToRecord [as runAction] (c:\Users\326eu\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:726:55)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\326eu\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (c:\Users\326eu\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at r (c:\Users\326eu\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:501:15)
```

</details>

**Comment by J-Fields** [comment]
Will be fixed in upcoming release
