### ISSUE TITLE
Failed to handle key={. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by Hau-Ng** [VSCodeVim/Vim#6962]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key={. Overlapping ranges are not allowed!
    at n._applyEdit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52275)
    at Object.edit (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:49967)
    at Object.executeTransformations (/home/admin217/.vscode/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:125:31)
    at j.runAction (/home/admin217/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (/home/admin217/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (/home/admin217/.vscode/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at /home/admin217/.vscode/extensions/vscodevim.vim-1.21.5/extensionBase.ts:370:73
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[2292, 39] | [2292, 39]]"
]
actionsRunPressedKeys: [
  "\n",
  "{"
]
actionsRun: [
  "$",
  "C",
  "C",
  "C",
  "C",
  "C",
  "C",
  "C",
  "C",
  "C",
  "C",
  "C",
  "C",
  "$",
  "C",
  "$"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 2292,
      "character": 39
    },
    "text": "Sc",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 2292,
        "character": 37
      },
      {
        "line": 2292,
        "character": 41
      }
    ],
    "text": "reScheduleCronJobRemindTelemed",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in 1.21.6
