### ISSUE TITLE
Failed to handle key=_. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by ms3273** [VSCodeVim/Vim#6966]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=_. Overlapping ranges are not allowed!
    at n._applyEdit (c:\Users\mayan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:52275)
    at Object.edit (c:\Users\mayan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:49967)
    at Object.executeTransformations (c:\Users\mayan\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\mayan\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at runMicrotasks (<anonymous>)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\mayan\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (c:\Users\mayan\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\mayan\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:370:73
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[608, 30] | [608, 30]]"
]
actionsRunPressedKeys: [
  "i",
  "_",
  "<Esc>"
]
actionsRun: [
  "ee",
  "$"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 608,
      "character": 30
    },
    "text": "_",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 608,
        "character": 12
      },
      {
        "line": 608,
        "character": 31
      }
    ],
    "text": "stripe_sub_item_id_dict",
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in 1.21.6
