### ISSUE TITLE
Failed to handle key=%3F. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by iMAGOx** [VSCodeVim/Vim#6968]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=%3F. Overlapping ranges are not allowed!
    at i._applyEdit (c:\Users\deoak\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:53357)
    at Object.edit (c:\Users\deoak\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:51029)
    at Object.executeTransformations (c:\Users\deoak\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\deoak\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\deoak\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (c:\Users\deoak\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\deoak\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:370:73
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[166, 0] | [166, 0]]"
]
actionsRunPressedKeys: [
  "I",
  "W",
  "a",
  "k",
  "t",
  "u",
  "I",
  "I",
  "I",
  "<BS>",
  "<BS>",
  ">",
  "%3F",
  "%3F"
]
actionsRun: [
  "Je",
  "$",
  "Je",
  "$t",
  "$t",
  "C",
  "C",
  "$"
]
textTransformations: [
  {
    "type": "deleteRange",
    "range": {
      "start": {
        "line": 61,
        "character": 5
      },
      "end": {
        "line": 61,
        "character": 8
      },
      "active": {
        "line": 61,
        "character": 8
      },
      "anchor": {
        "line": 61,
        "character": 5
      }
    },
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 61,
      "character": 8
    },
    "cursorIndex": 1
  },
  {
    "type": "deleteRange",
    "range": {
      "start": {
        "line": 61,
        "character": 46
      },
      "end": {
        "line": 61,
        "character": 49
      },
      "active": {
        "line": 61,
        "character": 49
      },
      "anchor": {
        "line": 61,
        "character": 46
      }
    },
    "cursorIndex": 2
  },
  {
    "type": "deleteText",
    "position": {
      "line": 166,
      "character": 0
    },
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment]
Any chance you remember what you were doing when this happened?
