### ISSUE TITLE
Failed to handle key=<BS>. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by jaikarans** [VSCodeVim/Vim#6969]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=<BS>. Overlapping ranges are not allowed!
    at i._applyEdit (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:52275)
    at Object.edit (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:49967)
    at Object.executeTransformations (/home/jaikaran/.vscode-oss/extensions/vscodevim.vim-1.21.5/src/transformations/execute.ts:125:31)
    at j.runAction (/home/jaikaran/.vscode-oss/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:727:13)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (/home/jaikaran/.vscode-oss/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:652:43)
    at j.mh [as handleKeyEvent] (/home/jaikaran/.vscode-oss/extensions/vscodevim.vim-1.21.5/src/mode/modeHandler.ts:471:11)
    at r (/home/jaikaran/.vscode-oss/extensions/vscodevim.vim-1.21.5/extensionBase.ts:501:15)
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[40, 7] | [40, 7]]"
]
actionsRunPressedKeys: [
  "<BS>",
  "<BS>",
  "<BS>"
]
actionsRun: [
  "$",
  "C",
  "C",
  "C"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 109,
      "character": 10
    },
    "text": " ",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 109,
        "character": 4
      },
      {
        "line": 109,
        "character": 11
      }
    ],
    "text": "(x i<0 || x j",
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 40,
      "character": 8
    },
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 40,
      "character": 7
    },
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 40,
      "character": 8
    },
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in 1.21.6
