### ISSUE TITLE
Failed to handle key=a. Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by AmalRichwin-AT** [VSCodeVim/Vim#6973]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=a. Overlapping ranges are not allowed!
    at i._applyEdit (c:\Users\amalr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:53357)
    at Object.edit (c:\Users\amalr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:51029)
    at Object.executeTransformations (c:\Users\amalr\.vscode\extensions\vscodevim.vim-1.21.5\src\transformations\execute.ts:125:31)
    at j.runAction (c:\Users\amalr\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:727:13)
    at process.actionToRecord (internal/process/task_queues.js:93:5)
    at j.handledAsAction [as handleKeyAsAnAction] (c:\Users\amalr\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:652:43)
    at j.text [as handleKeyEvent] (c:\Users\amalr\.vscode\extensions\vscodevim.vim-1.21.5\src\mode\modeHandler.ts:471:11)
    at c:\Users\amalr\.vscode\extensions\vscodevim.vim-1.21.5\extensionBase.ts:370:73
```

</details>

<details><summary>Additional context</summary>

```
currentMode: "Insert"
cursors: [
  "[[93, 43] | [93, 43]]"
]
actionsRunPressedKeys: [
  "<BS>",
  "<BS>",
  "<BS>",
  "a"
]
actionsRun: [
  "Qe",
  "q",
  "$",
  "C",
  "$",
  "C",
  "C",
  "C",
  "$"
]
textTransformations: [
  {
    "type": "insertText",
    "position": {
      "line": 93,
      "character": 46
    },
    "text": "lor",
    "cursorIndex": 0
  },
  {
    "type": "replaceText",
    "range": [
      {
        "line": 93,
        "character": 44
      },
      {
        "line": 93,
        "character": 49
      }
    ],
    "text": "color: colors.",
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 93,
      "character": 46
    },
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 93,
      "character": 45
    },
    "cursorIndex": 0
  },
  {
    "type": "deleteText",
    "position": {
      "line": 93,
      "character": 44
    },
    "cursorIndex": 0
  }
]
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in 1.21.6
