### ISSUE TITLE
Failed to handle key=j. command '<Esc>' not found

### ISSUE THREAD

**Issue by chrisbirster** [VSCodeVim/Vim#7004]
**To Reproduce**

1.  Go into "insert mode" 
2. Type "jj" to escape insert mode

I tried changing the key to  \<esc>, escape, \<ESC>. All with the same error. 

Here is my settings.json file:

{
    "files.autoSave": "onFocusChange",
    "vim.leader": "<space>",
    "vim.incsearch": true,
    "vim.useSystemClipboard": true,
    "vim.useCtrlKeys": true,
    "vim.hlsearch": true,
    "vim.normalModeKeyBindings": [
        {
            "before": ["\<tab>"],
            "commands": ["workbench.action.nextEditor"]
        },
        {
            "before": ["\<S-tab>"],
            "commands": ["workbench.action.previousEditor"]
        },
    ],
    "vim.insertModeKeyBindings": [
        {
            "before": ["j", "j"],
            "commands": ["\<Esc>"]
        },
    ],
    "vim.visualModeKeyBindings": [
        {
            "before": [">"],
            "commands": [">", "g", "v"]
        },
        {
            "before": ["\<"],
            "commands": ["\<", "g", "v"]
        },
    ],
     "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["\<C-n>"],
      "commands": [":nohl"]
    },
    {
      "before": ["\<leader>", "w"],
      "commands": ["workbench.action.splitEditor"]
    },
    {
      "before": ["\<leader>", "e"],
      "commands": ["workbench.action.toggleSidebarVisibility"]
    },
    {
      "before": ["\<leader>", "f"],
      "commands": ["revealInExplorer"]
    },
    {
      "before": ["\<leader>", "h"],
      "after": ["_"]
    },
    {
      "before": ["\<leader>", "l"],
      "after": ["$"]
    }
  ],
  "workbench.colorTheme": "Tailwind Moon",
  "window.zoomLevel": 1,
}

**VSCodeVim version**: 1.21.6

<details><summary>Stack trace</summary>

```
Error: command '<Esc>' not found
    at g._tryExecuteCommand (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:3364)
    at vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:3245
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

</details>

**Comment by chrisbirster** [comment]
I found my own mistake. I changed the insertModeKeyBindings to this:

"vim.insertModeKeyBindings": [
{
"before": ["j", "j"],
"after": ["<Esc>"]
},
],

I will close this...
