### ISSUE TITLE
Failed to handle key=(. Illegal value for `line`

### ISSUE THREAD

**Issue by YeaseonZhang** [VSCodeVim/Vim#7023]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=(. Illegal value for `line`
	at u._lineAt (/private/var/folders/mf/4yj9fkrn5lz3mlmvzynr9ffw0000gn/T/AppTranslocation/63582A11-BA33-4991-9D18-920B74C9396A/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:375:351)
	at Object.lineAt (/private/var/folders/mf/4yj9fkrn5lz3mlmvzynr9ffw0000gn/T/AppTranslocation/63582A11-BA33-4991-9D18-920B74C9396A/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:374:325)
	at Function.getLineAt (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:22504)
	at l.isLineBlank (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:12712)
	at l.getCurrentParagraphBeginning (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:13052)
	at l.getPreviousSentenceBeginWithRegex (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:16626)
	at l.getSentenceBegin (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:13299)
	at Je.execAction (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:209253)
	at Je.createMovementResult (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:158307)
	at Je.execActionWithCount (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:1:157964)
	at F.executeMovement (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:479356)
	at F.runAction (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:475260)
	at F.handleKeyAsAnAction (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:474718)
	at F.handleKeyEvent (/Users/taylorzhang/.vscode/extensions/vscodevim.vim-1.17.0/out/extension.js:9:471527)
```

</details>

**Comment by J-Fields** [comment]
You're on a very old version - please upgrade
