### ISSUE TITLE
vim v1.21.8 throwing extension host terminated error

### ISSUE THREAD

**Issue by roblevintennis** [VSCodeVim/Vim#7128]
**Describe the bug**
Editing an `angular.json` file I'd keep getting an error that `Extension host terminated unexpectedly`. 

**To Reproduce**

1.  Have vim plugin installed
2. Go to edit `angular.json` file (this is a standard angular json file generated when creating a. modern angular project

**Expected behavior**
Use vim as usual

**Actual**

I'd get thrown out of vim mode and can't in fact hit backspace so the file editing becomes unusable.

My vscode developer console tools showed:

```shell
  ERR ENOENT: no such file or directory, open '/Users/roblevin/Library/Application Support/Code/User/globalStorage/vscodevim.vim/.registers': Error: ENOENT: no such file or directory, open '/Users/roblevin/Library/Application Support/Code/User/globalStorage/vscodevim.vim/.registers'
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- 1.21.8
- VSCode version: 
```shell
Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z (1 wk ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

**Additional context**
Downgrading to `v1.21.7` appears to alleviate the issue for me

**Comment by roblevintennis** [comment]
Update. Still seeing issue after downgrade mentioned:

![image](https://user-images.githubusercontent.com/142403/135846930-5a5e6101-a1e5-465c-832b-8bdb93c26af9.png)

text

```shell


  ERR ENOENT: no such file or directory, open '/Users/roblevin/Library/Application Support/Code/User/globalStorage/vscodevim.vim/.registers': Error: ENOENT: no such file or directory, open '/Users/roblevin/Library/Application Support/Code/User/globalStorage/vscodevim.vim/.registers'


  ERR An unknown error occurred. Please consult the log for more details.

  ERR Request textDocument/hover failed with message: Language service does not have a program!: Error: Request textDocument/hover failed with message: Language service does not have a program!
    at handleResponse (/Users/roblevin/.vscode/extensions/angular.ng-template-12.2.0/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
    at processMessageQueue (/Users/roblevin/.vscode/extensions/angular.ng-template-12.2.0/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
    at Immediate.<anonymous> (/Users/roblevin/.vscode/extensions/angular.ng-template-12.2.0/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at processImmediate (internal/timers.js:461:21)



Extension host terminated unexpectedly. Code:  null  Signal:  SIGSEGV
_onExtensionHostCrashed @ abstractExtensionService.ts:615
log.ts:301 

  ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.configuration-editing, vscode.extension-editing, vscode.json-language-features, vscode.npm, webhint.vscode-webhint, vscode.debug-auto-launch, vscode.git, andyyaldoo.vscode-json, bierner.color-info, ecmel.vscode-html-css, firsttris.vscode-jest-runner, oderwat.indent-rainbow, PhilHindle.errorlens, vscodevim.vim, vscode.github, ms-vscode.js-debug, vscode.emmet, vscode.merge-conflict, dbaeumer.vscode-eslint, eamodio.gitlens, esbenp.prettier-vscode, nrwl.angular-console, usernamehw.errorlens, vscode.typescript-language-features, vscode.github-authentication, foxundermoon.shell-format, vscode.simple-browser, vscode.html-language-features, Angular.ng-template, VisualStudioExptTeam.vscodeintellicode, octref.vetur

```

**Comment by roblevintennis** [comment]
I'm going to close this out -- I did some more debugging and it seems I had two versions of `ErrorLens` installed and I removed the one by `Phil Hindle`-- `philhindle.errorlens` and left the one by user `Alexander` -- `usernamehw.errorlens`. I'm mad at myself for having two of these, but also wondering why they are both offered in the extension search. In any event, closing.
