### ISSUE TITLE
Failed to handle key=p. v.split is not a function

### ISSUE THREAD

**Issue by kiyoopoon** [VSCodeVim/Vim#7153]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.0

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key=p. v.split is not a function
	at n.exec (c:\Users\DELL\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:409622)
	at async n.execCount (c:\Users\DELL\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:1:37418)
	at async n.execCount (c:\Users\DELL\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:411621)
	at async F.runAction (c:\Users\DELL\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:475314)
	at async F.handleKeyAsAnAction (c:\Users\DELL\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:474707)
	at async F.handleKeyEvent (c:\Users\DELL\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:471516)
	at async Object.promise (c:\Users\DELL\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:235653)
	at async Object.runTasks (c:\Users\DELL\.vscode\extensions\vscodevim.vim-1.17.0\out\extension.js:9:621827)
```

</details>

**Comment by RakibHossen12** [comment]
Vim is very bad

I am a Senior Developer at Apple and Vim is so bad.... that I fill sad for it's developers...
