### ISSUE TITLE
Failed to handle key `%`: command 'extension.matchitJumpItems' not found

### ISSUE THREAD

**Issue by verbs2016** [VSCodeVim/Vim#7348]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.10

<details><summary>Stack trace</summary>

```
Error: command 'extension.matchitJumpItems' not found
    at y._tryExecuteCommand (vscode-file://vscode-app/d:/SoftwareDirectory/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1482:3364)
    at vscode-file://vscode-app/d:/SoftwareDirectory/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1482:3245
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

</details>

**Comment by verbs2016** [comment]
I'm very sorry, the reason is that I used someone else's configuration and didn't download the corresponding extensions.
