### ISSUE TITLE
Failed to handle key `<C-u>`: command 'cursorup' not found

### ISSUE THREAD

**Issue by Elesider** [VSCodeVim/Vim#7420]
**To Reproduce**
1. Add this to the setting for quick cursorup in the insert mode
 "vim.insertModeKeyBindingsNonRecursive": [
    {
      "before": ["<C-u>"],
      "commands": ["cursorup"]
    }
}
2. It can be resolved but command cusorup NOT found

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.21.10

<details><summary>Stack trace</summary>

```
Error: command 'cursorup' not found
    at y._tryExecuteCommand (vscode-file://vscode-app/c:/Users/ZNI2/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1482:3364)
    at vscode-file://vscode-app/c:/Users/ZNI2/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1482:3245
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

</details>

**Comment by Elesider** [comment]
Thanks. It works good now!
