### ISSUE TITLE
Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by jkhdr5426** [VSCodeVim/Vim#7480]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.22.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'substring' of undefined
    at C.display (/Users/edwardkim/.vscode/extensions/vscodevim.vim-1.22.1/src/cmd_line/commandLine.ts:223:21)
    at statusBarText (/Users/edwardkim/.vscode/extensions/vscodevim.vim-1.22.1/src/statusBar.ts:205:35)
    at Object.clear (/Users/edwardkim/.vscode/extensions/vscodevim.vim-1.22.1/src/statusBar.ts:105:17)
    at j.handleKeyEvent (/Users/edwardkim/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:514:17)
    at process.mh (internal/process/task_queues.js:93:5)
    at r (/Users/edwardkim/.vscode/extensions/vscodevim.vim-1.22.1/extensionBase.ts:518:15)
```

</details>

**Comment by J-Fields** [comment]
Duplicate of #7512
