### ISSUE TITLE
Failed to handle key `<Del>`: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by bogolas** [VSCodeVim/Vim#7492]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.22.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key `<Del>`: Cannot read property 'length' of undefined
    at _.delete (/home/bodi/.vscode/extensions/vscodevim.vim-1.22.1/src/cmd_line/commandLine.ts:131:47)
    at _.run (/home/bodi/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/commands/commandLine.ts:185:23)
    at _.exec (/home/bodi/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/commands/commandLine.ts:30:16)
    at _.execCount (/home/bodi/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/base.ts:199:20)
    at j.runAction (/home/bodi/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:715:20)
    at j.handleKeyAsAnAction (/home/bodi/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:666:16)
    at j.handleKeyEvent (/home/bodi/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:478:40)
    at process.mh (internal/process/task_queues.js:93:5)
    at r (/home/bodi/.vscode/extensions/vscodevim.vim-1.22.1/extensionBase.ts:518:15)
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in 1.22.2 by #7513
