### ISSUE TITLE
Failed to handle key `<down>`: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by exokkmpf** [VSCodeVim/Vim#7497]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.22.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key `<down>`: Cannot read property 'length' of undefined
    at C.historyForward (c:\Users\kkumpf\.vscode\extensions\vscodevim.vim-1.22.1\src\cmd_line\commandLine.ts:110:34)
    at O.run (c:\Users\kkumpf\.vscode\extensions\vscodevim.vim-1.22.1\src\actions\commands\commandLine.ts:257:23)
    at O.exec (c:\Users\kkumpf\.vscode\extensions\vscodevim.vim-1.22.1\src\actions\commands\commandLine.ts:30:16)
    at O.execCount (c:\Users\kkumpf\.vscode\extensions\vscodevim.vim-1.22.1\src\actions\base.ts:199:20)
    at j.runAction (c:\Users\kkumpf\.vscode\extensions\vscodevim.vim-1.22.1\src\mode\modeHandler.ts:715:20)
    at j.handleKeyAsAnAction (c:\Users\kkumpf\.vscode\extensions\vscodevim.vim-1.22.1\src\mode\modeHandler.ts:666:16)
    at j.handleKeyEvent (c:\Users\kkumpf\.vscode\extensions\vscodevim.vim-1.22.1\src\mode\modeHandler.ts:478:40)
    at runMicrotasks (<anonymous>)
    at process.mh (internal/process/task_queues.js:93:5)
    at r (c:\Users\kkumpf\.vscode\extensions\vscodevim.vim-1.22.1\extensionBase.ts:518:15)
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in 1.22.2 by #7513
