### ISSUE TITLE
Failed to handle key `<Esc>`: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by M0rfes** [VSCodeVim/Vim#7500]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.22.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key `<Esc>`: Cannot read property 'length' of undefined
    at _.escape (/Users/morfes/.vscode/extensions/vscodevim.vim-1.22.1/src/cmd_line/commandLine.ts:528:19)
    at runMicrotasks (<anonymous>)
    at process.commandLine (internal/process/task_queues.js:93:5)
    at M.run (/Users/morfes/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/commands/commandLine.ts:166:52)
    at M.i [as exec] (/Users/morfes/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/commands/commandLine.ts:28:54)
    at M.execCount (/Users/morfes/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/base.ts:198:42)
    at j.actionToRecord [as runAction] (/Users/morfes/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:714:47)
    at j.handledAsAction [as handleKeyAsAnAction] (/Users/morfes/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:663:43)
    at j.mh [as handleKeyEvent] (/Users/morfes/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:478:11)
    at /Users/morfes/.vscode/extensions/vscodevim.vim-1.22.1/extensionBase.ts:512:53
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in 1.22.2 by #7513
