### ISSUE TITLE
Mark not set

### ISSUE THREAD

**Issue by CarpentersKeys** [VSCodeVim/Vim#7504]
**To Reproduce**

1 highlight some text in vscode
2 shift + ':'
3 's/'
errors on slash

**VSCodeVim version**: 1.22.1

<details><summary>Stack trace</summary>

```
Error: Mark not set
    at Function.fromCode (c:\Users\Joshua\.vscode\extensions\vscodevim.vim-1.22.1\src\error.ts:94:14)
    at c:\Users\Joshua\.vscode\extensions\vscodevim.vim-1.22.1\src\vimscript\lineRange.ts:152:28
    at h.resolve (c:\Users\Joshua\.vscode\extensions\vscodevim.vim-1.22.1\src\vimscript\lineRange.ts:126:18)
    at f.resolve (c:\Users\Joshua\.vscode\extensions\vscodevim.vim-1.22.1\src\vimscript\lineRange.ts:310:29)
    at l.allMatches (c:\Users\Joshua\.vscode\extensions\vscodevim.vim-1.22.1\src\vimscript\pattern.ts:82:34)
    at M.getSubstitutionDecorations (c:\Users\Joshua\.vscode\extensions\vscodevim.vim-1.22.1\src\cmd_line\commands\substitute.ts:267:30)
    at C.getDecorations (c:\Users\Joshua\.vscode\extensions\vscodevim.vim-1.22.1\src\cmd_line\commandLine.ts:253:22)
    at j.updateSearchHighlights (c:\Users\Joshua\.vscode\extensions\vscodevim.vim-1.22.1\src\mode\modeHandler.ts:1141:36)
    at j.updateView (c:\Users\Joshua\.vscode\extensions\vscodevim.vim-1.22.1\src\mode\modeHandler.ts:1545:49)
    at _ (c:\Users\Joshua\.vscode\extensions\vscodevim.vim-1.22.1\extensionBase.ts:54:22)
    at process.mh (internal/process/task_queues.js:93:5)
    at c:\Users\Joshua\.vscode\extensions\vscodevim.vim-1.22.1\extensionBase.ts:264:15
```

</details>

**Comment by J-Fields** [comment]
@CarpentersKeys Can you still repro on 1.22.2?
