### ISSUE TITLE
Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by bnmouli-coefficient** [VSCodeVim/Vim#7507]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.22.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'substring' of undefined
    at _.display (/Users/chandramoulibanavara/.vscode/extensions/vscodevim.vim-1.22.1/src/cmd_line/commandLine.ts:402:89)
    at statusBarText (/Users/chandramoulibanavara/.vscode/extensions/vscodevim.vim-1.22.1/src/statusBar.ts:199:35)
    at Object.clear (/Users/chandramoulibanavara/.vscode/extensions/vscodevim.vim-1.22.1/src/statusBar.ts:105:17)
    at j.handleKeyEvent (/Users/chandramoulibanavara/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:514:17)
    at runMicrotasks (<anonymous>)
    at process.mh (internal/process/task_queues.js:93:5)
    at r (/Users/chandramoulibanavara/.vscode/extensions/vscodevim.vim-1.22.1/extensionBase.ts:518:15)
```

</details>

**Comment by J-Fields** [comment]
Duplicate of #7512
