### ISSUE TITLE
Failed to handle key `<down>`: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Justnewcoder** [VSCodeVim/Vim#7508]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.22.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key `<down>`: Cannot read property 'length' of undefined
    at C.historyForward (/Users/kirillkisner/.vscode/extensions/vscodevim.vim-1.22.1/src/cmd_line/commandLine.ts:110:34)
    at O.run (/Users/kirillkisner/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/commands/commandLine.ts:257:23)
    at O.exec (/Users/kirillkisner/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/commands/commandLine.ts:30:16)
    at O.execCount (/Users/kirillkisner/.vscode/extensions/vscodevim.vim-1.22.1/src/actions/base.ts:199:20)
    at j.runAction (/Users/kirillkisner/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:715:20)
    at j.handleKeyAsAnAction (/Users/kirillkisner/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:666:16)
    at j.handleKeyEvent (/Users/kirillkisner/.vscode/extensions/vscodevim.vim-1.22.1/src/mode/modeHandler.ts:478:40)
    at runMicrotasks (<anonymous>)
    at process.mh (internal/process/task_queues.js:93:5)
    at r (/Users/kirillkisner/.vscode/extensions/vscodevim.vim-1.22.1/extensionBase.ts:518:15)
```

</details>

**Comment by J-Fields** [comment]
Should be fixed in 1.22.2 by #7513
