### ISSUE TITLE
Error on Search 

### ISSUE THREAD

**Issue by jvbianchi** [VSCodeVim/Vim#786]
### What did you do?

Make a search and clicked on the results.
Sometimes you have to click in many results for this to happen.

### What happened instead?
Error appear on the developer tools

`shell.ts:424Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at Function.readLineAt (/Users/victor/.vscode-insiders/extensions/vscodevim.vim-0.1.10/out/src/textEditor.js:114:53)
    at Function.getLineLength (/Users/victor/.vscode-insiders/extensions/vscodevim.vim-0.1.10/out/src/motion/position.js:444:40)
    at Position.getLineEnd (/Users/victor/.vscode-insiders/extensions/vscodevim.vim-0.1.10/out/src/motion/position.js:372:49)
    at ModeHandler.<anonymous> (/Users/victor/.vscode-insiders/extensions/vscodevim.vim-0.1.10/out/src/mode/modeHandler.js:434:58)
    at next (<anonymous>)
    at /Users/victor/.vscode-insiders/extensions/vscodevim.vim-0.1.10/out/src/mode/modeHandler.js:7:65
    at __awaiter (/Users/victor/.vscode-insiders/extensions/vscodevim.vim-0.1.10/out/src/mode/modeHandler.js:3:12)
    at ModeHandler.vscode.window.onDidChangeTextEditorSelection (/Users/victor/.vscode-insiders/extensions/vscodevim.vim-0.1.10/out/src/mode/modeHandler.js:408:61)
    at e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:5124)
    at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:13320)`

### Technical details:

* VSCode Version: vscode-insiders (1.6.0-insider)
* VsCodeVim Version: 0.1.10
* OS: Mac 10.11.6

**Comment by rebornix** [comment]
Can't believe it's so easy to reproduce ...

**Comment by rebornix** [comment]
We need a way to guard `document`. This issue shares the same solution for #775 so let's track it there.
