### ISSUE TITLE
Failed to handle key `s`: Cannot read properties of undefined (reading 'fileName')

### ISSUE THREAD

**Issue by tobbstr** [VSCodeVim/Vim#7895]
**To Reproduce**

1.  When I use my VIM shortcut defined as:

```json
{
            "before": ["<leader>", "f", "s"],
            "commands": ["go.fill.struct"]
}
```

or run the command `Go: Fill struct` I get the error message below.

2.  I see the error:

> Failed to handle key `s`: Cannot read properties of undefined (reading 'fileName')

Side note! It used to work. I haven't changed any keyboard shortcuts but I have updated VSCode and my installed extensions.

**VSCodeVim version**: 1.23.2

<details><summary>Stack trace</summary>

```
TypeError: Cannot read properties of undefined (reading 'fileName')
    at getCommonArgs (/Users/tobstr/.vscode/extensions/golang.go-0.35.1/dist/goMain.js:78352:24)
    at /Users/tobstr/.vscode/extensions/golang.go-0.35.1/dist/goMain.js:78341:16
    at a._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63922)
    at a._doExecuteCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:62740)
    at a.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:62600)
    at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:31928)
    at p.handleRemapping (/Users/tobstr/.vscode/extensions/vscodevim.vim-1.23.2/src/configuration/remapper.ts:519:35)
    at p.sendKey (/Users/tobstr/.vscode/extensions/vscodevim.vim-1.23.2/src/configuration/remapper.ts:369:20)
    at t.Remappers.sendKey (/Users/tobstr/.vscode/extensions/vscodevim.vim-1.23.2/src/configuration/remapper.ts:39:26)
    at process.handledAsRemap (node:internal/process/task_queues:96:5)
    at N.text [as handleKeyEvent] (/Users/tobstr/.vscode/extensions/vscodevim.vim-1.23.2/src/mode/modeHandler.ts:487:9)
    at /Users/tobstr/.vscode/extensions/vscodevim.vim-1.23.2/extensionBase.ts:359:73
```

</details>

**Comment by camza-varnish** [comment]
It's also reproducible on 1.74.3
