### ISSUE TITLE
Failed to handle key `2`: Cannot read properties of undefined (reading 'uri')

### ISSUE THREAD

**Issue by sabinm677** [VSCodeVim/Vim#8059]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.24.1

<details><summary>Stack trace</summary>

```
TypeError: Failed to handle key `2`: Cannot read properties of undefined (reading 'uri')
    at u.execute (c:\Users\Acer\.vscode\extensions\vscodevim.vim-1.24.1\src\cmd_line\commands\tab.ts:159:52)
    at p.handleRemapping (c:\Users\Acer\.vscode\extensions\vscodevim.vim-1.24.1\src\configuration\remapper.ts:512:44)
    at p.sendKey (c:\Users\Acer\.vscode\extensions\vscodevim.vim-1.24.1\src\configuration\remapper.ts:369:20)
    at t.Remappers.sendKey (c:\Users\Acer\.vscode\extensions\vscodevim.vim-1.24.1\src\configuration\remapper.ts:39:26)
    at process.handledAsRemap (node:internal/process/task_queues:96:5)
    at N.text [as handleKeyEvent] (c:\Users\Acer\.vscode\extensions\vscodevim.vim-1.24.1\src\mode\modeHandler.ts:486:9)
    at c:\Users\Acer\.vscode\extensions\vscodevim.vim-1.24.1\extensionBase.ts:359:73
```

</details>

**Comment by sabinm677** [comment]
Second tab was VSCode get started page. When I try to switch to second tab it is showing this error.

My mapping
```
nmap <Leader>2 :tabn 2<cr>
```

**Comment by Buzzkill-McSquare** [comment]
There seems to be a general error with the `:tabn` command. I've noticed that it always tabs from the first editor tab regardless of focus, it doesn't wrap and some number arguments result in the same error that @sabinm677 posted.

The `:tabp` command works fine - it'll take any number and wrap around the group's tabs if the argument exceeds the number of tabs.

**Comment by sabinm677** [comment]
Any update on this issue?
