### ISSUE TITLE
Press `o` to start a newline,  the newline is removed when following lines are blank lines

### ISSUE THREAD

**Issue by hitzhangjie** [VSCodeVim/Vim#8208]
**Describe the bug**
When I in normal mode, I press `o` to start a newline. First, it start a newline correctly, but after a little time (<=1s), it jump back to the original line, and the generated newline just now is removed.

It looks like some formatting action executed, I don't know what happened. And I don't know how to view the extension logging.

**To Reproduce**

1.  In normal mode, press `o` to start a newline
2.  wait a little time
3.  the cursor jump back to original line and the newline created just now is removed

**Expected behavior**
start a newline correctly

**Screenshots**
https://user-images.githubusercontent.com/3725760/211965035-7f883e9a-f67f-4ca8-bec5-942131cb5a49.mp4

**Environment (please complete the following information):**

I use vscode remote:

Here's the **remote extension host** output:
```
2023-01-12 10:20:07.757 [info] Extension host with pid 9946 started
2023-01-12 10:20:07.771 [info] Lock '/root/.vscode-server/data/User/workspaceStorage/02931c054405dfec750a81b719544d10/vscode.lock': Lock acquired.
2023-01-12 10:20:07.847 [info] ExtensionService#_doActivateExtension HarryHopkinson.vs-code-runner, startup: false, activationEvent: 'onLanguage:code-runner-output'
2023-01-12 10:20:07.848 [info] ExtensionService#_doActivateExtension aleksandra.go-group-imports, startup: false, activationEvent: 'onLanguage:go'
2023-01-12 10:20:07.848 [info] ExtensionService#_doActivateExtension galkowskit.go-interface-annotations, startup: false, activationEvent: 'onLanguage:go'
2023-01-12 10:20:07.848 [info] ExtensionService#_doActivateExtension golang.go, startup: false, activationEvent: 'onLanguage:go'
2023-01-12 10:20:07.848 [info] ExtensionService#_doActivateExtension quillaja.goasm, startup: false, activationEvent: 'onLanguage:go'
2023-01-12 10:20:07.849 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-01-12 10:20:07.849 [info] ExtensionService#_doActivateExtension christian-kohler.path-intellisense, startup: true, activationEvent: '*'
2023-01-12 10:20:07.849 [info] ExtensionService#_doActivateExtension mhutchie.git-graph, startup: true, activationEvent: '*'
2023-01-12 10:20:07.849 [info] ExtensionService#_doActivateExtension saekiraku.pin-up, startup: true, activationEvent: '*'
2023-01-12 10:20:08.394 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
2023-01-12 10:20:08.394 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-01-12 10:20:08.395 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-01-12 10:20:08.395 [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker, startup: false, activationEvent: 'onLanguage:jsonc'
2023-01-12 10:20:08.603 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-01-12 10:20:08.604 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-01-12 10:20:09.239 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-01-12 10:20:09.239 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
2023-01-12 10:20:09.239 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-01-12 10:20:09.240 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onStartupFinished', root cause: esbenp.prettier-vscode
2023-01-12 10:20:09.240 [info] ExtensionService#_doActivateExtension maattdd.gitless, startup: false, activationEvent: 'onStartupFinished'
2023-01-12 10:20:09.240 [info] ExtensionService#_doActivateExtension stylelint.vscode-stylelint, startup: false, activationEvent: 'onStartupFinished'
2023-01-12 10:20:09.241 [info] ExtensionService#_doActivateExtension vadimcn.vscode-lldb, startup: false, activationEvent: 'onStartupFinished'
2023-01-12 10:20:09.241 [info] Eager extensions activated
2023-01-12 10:20:10.218 [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode, startup: false, activationEvent: 'onStartupFinished'
```
Here is **the extension host**:
```
2023-01-12 10:20:06.312 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-ssh, startup: false, activationEvent: 'onResolveRemoteAuthority:ssh-remote'
2023-01-12 10:20:06.374 [info] $resolveAuthority invoked for authority (ssh-remote)
2023-01-12 10:20:07.763 [info] ExtensionService#_doActivateExtension stkb.rewrap, startup: true, activationEvent: '*'
2023-01-12 10:20:07.763 [info] ExtensionService#_doActivateExtension vscodevim.vim, startup: true, activationEvent: '*'
2023-01-12 10:20:07.833 [info] ExtensionService#_doActivateExtension ms-vscode.remote-explorer, startup: false, activationEvent: 'onCommand:remote-internal.setActiveFolders'
2023-01-12 10:20:07.833 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-01-12 10:20:08.318 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-01-12 10:20:08.318 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onLanguage:jsonc'
2023-01-12 10:20:08.786 [info] Eager extensions activated
2023-01-12 10:20:08.789 [info] ExtensionService#_doActivateExtension alefragnani.Bookmarks, startup: false, activationEvent: 'onStartupFinished'
2023-01-12 10:20:08.789 [info] ExtensionService#_doActivateExtension PKief.material-icon-theme, startup: false, activationEvent: 'onStartupFinished'
```

- Extension (VsCodeVim) version: v1.24.3
- VSCode version: v1.74.3
- OS: macOS 13.1 (22C65)

**Additional context**
It works before, It happened these days, I didn't change vim extension settings these days. The extensions installed in local and remote host, I install and uninstall several plugins, but I am not sure If there's other plugins conflict or not.

You can see the video attached, it looks like a formatting action is executed when I start a newline.
- If I start a newline in a position where lines before and following lines are not blank lines, it works as expected.
- If I start a newline in a position where following lines are blank lines, the bug occurred.

**Comment by hitzhangjie** [comment]
I disabled the formatter, the problem still exists.

And when I reload the extensions, I see vim logging error:
```
2023-01-12 11:10:21.566 [info] Extension host terminating: received terminate message from renderer
2023-01-12 11:10:21.759 [error] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 't'
    |     property '_readableState' -> object with constructor 'M'
    |     property 'pipes' -> object with constructor 'Array'
    |     index 0 -> object with constructor 't.ConsoleForElectron'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at /Users/zhangjie/.vscode/extensions/vscodevim.vim-1.24.3/src/register/register.ts:333:16
    at process.async (node:internal/process/task_queues:96:5)
    at Object.e.deactivate (/Users/zhangjie/.vscode/extensions/vscodevim.vim-1.24.3/extension.ts:64:8)
    at async Promise.all (index 8)
    at d.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:9315)
```

**Comment by hitzhangjie** [comment]
I uninstalled plugin, and reinstall it again. Now it works. For there's no any conversation and reply on this. I will close it.

**Comment by hitzhangjie** [comment]
I reset the settings `use keymapping from .vimrc`, now it works. There must be some conflicts or other problems when using .vimrc.

I'll close this.

**Comment by hitzhangjie** [comment]
The problem still reproducible.

**Comment by hitzhangjie** [comment]
Maybe it's caused by another extension `Go Group Imports`, https://github.com/beerose/go-group-imports-vscode.

I disable `Go Group Imports`, now vscodevim works as expected.
