### ISSUE TITLE
Failed to handle key ` `: command 'whichkey.show' not found

### ISSUE THREAD

**Issue by fathulfahmy** [VSCodeVim/Vim#8264]
**To Reproduce**

1.  Go to Github Codespaces on mobile browser
3. Install Which Key extension
4.  Keybind spacebar on vimvscode normal mode to call Which Key menu
5. Add Codespaces to mobile/tablet homepage
6. Open codespace from mobile/tablet homepage
7. Open any text or code to edit
8. Press spacebar on vimvscode normal mode
9.  See error

**VSCodeVim version**: 1.24.3

<details><summary>Stack trace</summary>

```
Error: command 'whichkey.show' not found
    at b.k (https://main.vscode-cdn.net/stable/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/workbench/workbench.web.main.js:1583:2620)
    at b.executeCommand (https://main.vscode-cdn.net/stable/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/workbench/workbench.web.main.js:1583:2536)
```

</details>

![Screenshot_20230224_160945_Chrome](https://user-images.githubusercontent.com/100550389/221126403-f3dfc6d4-e65e-4b8c-b37d-3d9a383ee848.jpg)
![Screenshot_20230224_160930_Chrome](https://user-images.githubusercontent.com/100550389/221126411-3a83a667-2f5a-4e72-b4c6-50e0e5ab4d4c.jpg)
![Screenshot_20230224_161137_Chrome](https://user-images.githubusercontent.com/100550389/221127072-a4c19c0d-1f94-4374-8684-fef19e176847.jpg)

**Comment by fathulfahmy** [comment]
I was trying Codespace feature on my tablet, all of my synced settings works fine on Codespace through the web browser. However, after adding Codespace to homescreen, i noticed i was unable to call WhichKey menu using spacebar that i has set on vim normal mode keybind.
