### ISSUE TITLE
Failed to handle key=:. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by Homqyy** [VSCodeVim/Vim#8305]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.5

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=:. HistoryTracker:Tried to modify history at index -1
    at h.get currentHistoryStep [as currentHistoryStep] (c:\Users\homqyy\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:200309)
    at h._isDocumentTextNeeded (c:\Users\homqyy\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:203302)
    at h.addChange (c:\Users\homqyy\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:203495)
    at F.handleKeyAsAnAction (c:\Users\homqyy\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:169454)
    at F.handleKeyEvent (c:\Users\homqyy\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:167823)
    at Object.promise (c:\Users\homqyy\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:9:216269)
    at Object.runTasks (c:\Users\homqyy\.vscode\extensions\vscodevim.vim-1.18.5\out\extension.js:11:327644)
```

</details>

**Comment by J-Fields** [comment]
This is a very old version of VSCodeVim; please upgrade
