### ISSUE TITLE
Failed to handle key=u. HistoryTracker:Tried to modify history at index -1

### ISSUE THREAD

**Issue by Testare** [VSCodeVim/Vim#8484]
**To Reproduce**

1. Edit a file
2. Save with ":w"
3. Hit undo (perhaps a couple times)
4. Error occurs, if the undo is even successful
5. I'm unable to edit the file anymore, the error just pops up whenever I try. I have to close all editors of the file (either saving my mistake or losing my work) and re-open.

I've also had it happen before that I'll do something like type or remove text and hit the undo functionality right after but the undo won't undo the change.

I'm not sure it's related, but I do use a lot of vim/nvim, and they sometimes tell me things about incompatible undo files when I use both on the same file. I think most of that happens in a different environment though, so I'm not sure it's related.

Thank you very much for helping support us who got hooked on vim keybindings and want to use them in our other environments =]

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
Error: Failed to handle key=u. HistoryTracker:Tried to modify history at index -1
	at get currentHistoryStep [as currentHistoryStep] (/home/testare/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:11:155484)
	at h.goBackHistoryStep (/home/testare/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:11:160614)
	at Ie.exec (/home/testare/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:1:101096)
	at Ie.execCount (/home/testare/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:1:37021)
	at F.runAction (/home/testare/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:11:121930)
	at F.handleKeyAsAnAction (/home/testare/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:11:121326)
	at F.handleKeyEvent (/home/testare/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:11:118135)
	at async Object.promise (/home/testare/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:9:234345)
	at async Object.runTasks (/home/testare/.vscode-oss/extensions/vscodevim.vim-1.17.1/out/extension.js:11:282242)
```

</details>

**Comment by J-Fields** [comment]
You're using a very old version of the extension; please upgrade
