### ISSUE TITLE
"Window frozen": Unresponsive extension: errors thrown from getConfiguration

### ISSUE THREAD

**Issue by ulugbekna** [VSCodeVim/Vim#8749]
Thank you for a great extension! 

**Describe the bug**

None of the movement keys (haven't checked other keys) were working for several seconds as if the window froze. I see several errors in the dev console: 

<details>
 INFO Extension host (LocalProcess pid: 88104) is unresponsive.
localProcessExtensionHost.ts:273 Extension Host
localProcessExtensionHost.ts:274 Debugger attached.
log.ts:421  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:421  INFO Extension host (LocalProcess pid: 88104) is responsive.
log.ts:421  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
log.ts:441   ERR 
	 at $ (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:37478)
	 at getConfiguration (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:43554)
	 at getConfiguration (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:37757)
	 at getConfiguration (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:574622)
	 at get (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:575618)
	 at f (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:714448)
	 at p (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:717437)
	 at t.prevWordStart (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:717827)
	 at h.Position.prevWordStart (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:562237)
	 at execAction (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:386849)
	 at execActionWithCount (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:227518)
	 at executeMovement (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:648196)
	 at runAction (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:644078)
	 at handleKeyAsAnAction (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:642017)
	 at handleKeyEvent (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:638750)
log.ts:441   ERR 
	 at (anonymous) (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:714491)
	 at f (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:714448)
	 at p (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:717437)
	 at t.prevWordStart (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:717827)
	 at h.Position.prevWordStart (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:562237)
	 at execAction (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:386849)
	 at execActionWithCount (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:227518)
log.ts:441   ERR 
	 at (anonymous) (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:37546)
	 at $ (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:37478)
	 at getConfiguration (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:43554)
	 at getConfiguration (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:37757)
	 at getConfiguration (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:574622)
	 at get (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:575618)
	 at f (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:714448)
	 at p (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:717437)
	 at t.prevWordStart (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:717827)
	 at h.Position.prevWordStart (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:562237)
	 at execAction (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:386849)
	 at execActionWithCount (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:227518)
	 at executeMovement (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:648196)
	 at runAction (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:644078)
	 at handleKeyAsAnAction (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:642017)
	 at handleKeyEvent (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:638750)
log.ts:441   ERR 
	 at get (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:45431)
	 at (anonymous) (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:37546)
	 at $ (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:37478)
	 at getConfiguration (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:43554)
	 at getConfiguration (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:37757)
	 at getConfiguration (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:574622)
	 at get (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:575618)
	 at f (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:714448)
	 at p (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:717437)
	 at t.prevWordStart (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:717827)
	 at h.Position.prevWordStart (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:562237)
	 at execAction (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:386849)
	 at execActionWithCount (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:227518)
log.ts:441   ERR 
	 at f (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:714448)
	 at p (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:717437)
	 at t.prevWordStart (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:717827)
	 at h.Position.prevWordStart (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:562237)
	 at execAction (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:386849)
	 at execActionWithCount (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:227518)
	 at executeMovement (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:648196)
	 at runAction (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:644078)
	 at handleKeyAsAnAction (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:642017)
	 at handleKeyEvent (file:///Users/ulugbekna/.vscode-insiders/extensions/vscodevim.vim-1.27.1/out/extension.js:2:638750)
log.ts:431  WARN UNRESPONSIVE extension host: 'vscodevim.vim' took 34.132440921510096% of 280.583ms, saved PROFILE here: 'file:///var/folders/ws/lk9gx2fn7qx09jl2l5zf6jwr0000gn/T/exthost-99b0be.cpuprofile'
</details> 

**To Reproduce**

Don't have a repro step

**Screenshots**

<img width="1546" alt="image" src="https://github.com/VSCodeVim/Vim/assets/16353531/a6f792d7-d12b-4225-8b8f-22a22f6c8acf">

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.27.1
- VSCode version:

Version: 1.85.0-insider
Commit: ef71b038ad2518e32514b6cc3a4df9f94c096e65
Date: 2023-11-23T05:47:58.884Z
Electron: 25.9.4
ElectronBuildId: 25127168
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

**Comment by ulugbekna** [comment]
CPU profile
[exthost-99b0be.cpuprofile](https://github.com/VSCodeVim/Vim/files/13451698/exthost-99b0be.cpuprofile)
