### ISSUE TITLE
TypeError: r.some is not a function

### ISSUE THREAD

**Issue by AlaricWeb** [VSCodeVim/Vim#8976]
Type: <b>Performance Issue</b>

 [error] TypeError: r.some is not a function
	at d.saveToDisk (c:\Users\artist\.vscode\extensions\vscodevim.vim-1.27.2\out\extension.js:2:675367)
	at t.deactivate (c:\Users\artist\.vscode\extensions\vscodevim.vim-1.27.2\out\extension.js:2:213749)
	at m.eb (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:9772)
	at c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:7816
	at Array.map (<anonymous>)
	at m.$ (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:7803)
	at m.terminate (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:8077)
	at a.terminate (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:162:1513)
	at t (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:175:9917)
	at MessagePortMain.<anonymous> (c:\Users\artist\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:175:6342)
	at MessagePortMain.emit (node:events:517:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)

Extension version: 1.27.2
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.58GB (8.66GB free)|
|Process Argv|E:\\workspace\\vuetest --crash-reporter-id 3262224c-f1f5-4560-bf2c-e862bbe2108e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   142	 11616	code main
    0	   179	  1072	extensionHost [1]
    0	   128	  4484	     electron-nodejs (tsserver.js )
    0	  1351	 12312	     electron-nodejs (tsserver.js )
    0	    94	  6908	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	   137	  1464	shared-process
    0	   100	  1600	window [2] (Issue Reporter)
    0	    29	  6992	   crashpad-handler
    0	    95	  7248	fileWatcher [1]
    0	    44	  7544	   utility-network-service
    0	    99	 10388	ptyHost
    0	     6	 11984	     conpty-agent
    0	     5	 12508	     "C:\Program Files\Git\bin\bash.exe" --login -i
    0	    11	  9492	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --login -i
    2	   297	 10684	window [1] (auto-imports.d.ts - blueHat - Visual Studio Code)
    1	   267	 10980	   gpu-process
    0	   110	 12380	extensionHost [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (auto-imports.d.ts - blueHat - Visual Studio Code)
|    Folder (blueHat): 71 files
|      File types: ts(16) vue(12) json(6) md(4) svg(2) env(1) yml(1)
|                  gitignore(1) html(1) yaml(1)
|      Conf files: github-actions(1) settings.json(1) package.json(1)
|                  tsconfig.json(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by mathieupost** [comment]
Same issue. Located here https://github.com/VSCodeVim/Vim/blob/0cb62c44bb7567f62b72557524416dd8515d434f/src/register/register.ts#L317

I'll take a look when I have time
