### ISSUE TITLE
Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by jvbianchi** [VSCodeVim/Vim#905]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----
This error appears in the Developer tools a bunch of times: 

`
shell.ts:438Cannot read property 'dispose' of undefined: TypeError: Cannot read property 'dispose' of undefined
    at vscode.workspace.onDidCloseTextDocument (/Users/victor/.vscode-insiders/extensions/vscodevim.vim-0.3.7/out/extension.js:127:45)
    at e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:5675)
    at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:13998)
    at t.$acceptModelRemoved (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:10:23043)
    at t.e.handle (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:9:28684)
    at s (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:7:6447)
    at p (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:7:7124)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:438
`

### Technical details:

* VSCode Version: 1.7.0-insider (1.7.0-insider)
* VsCodeVim Version: 0.3.7
* OS: Mac OSX

**Comment by xconverge** [comment]
reproduced it, thanks!
