### ISSUE TITLE
vscodevim stopped working sometimes until reinstalling the extension

### ISSUE THREAD

**Issue by JasonXJ** [VSCodeVim/Vim#9132]
**Describe the bug**
I am using the web version of vscode (i.e. `code serve-web ...`). Sometimes vscodevim just stopped working. The developer console would have these log:

```
2024-07-15 10:22:59.268 [info] Extension host started
2024-07-15 10:22:59.620 [info] Eager extensions activated
2024-07-15 10:22:59.638 [info] ExtensionService#_doActivateExtension vscodevim.vim, startup: false, activationEvent: 'onStartupFinished'
2024-07-15 10:22:59.665 [error] Activating extension vscodevim.vim failed due to an error:
2024-07-15 10:22:59.665 [error] Error: Not Found
	at R.xb (../../../vs/workbench/api/worker/extensionHostWorker.js:111:53700)
	at async Promise.all (index 0)
	at async n (../../../vs/workbench/api/worker/extensionHostWorker.js:96:6385)
	at async n.m (../../../vs/workbench/api/worker/extensionHostWorker.js:96:6348)
	at async n.l (../../../vs/workbench/api/worker/extensionHostWorker.js:96:5805)
```

This issue won't go away when I reloaded the browser window or restarted the code server. It did go away if I re-installed the extension and then reloaded the window.

**To Reproduce**
I don't know how to repro this. It just happenes sometimes.

**Environment (please complete the following information):**

Extension version: 1.27.3

vscode:
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: server-distro

OS: linux (debian)

**Comment by andrewpollock** [comment]
I also suffer from this problem, with the same runtime environment.

**Comment by julabs** [comment]
The same problem occurs on Linux Debian.

**Comment by andrewpollock** [comment]
I've just encountered this again and before I do the reinstallation dance, wanted to see what debugging information I could capture. So far, I know that the VS Code package was recently upgraded to 1.92.0 and my virtual machine was rebooted. Looks like the reboot was the most recent thing:

```
2024-08-02 12:52:24 upgrade code:amd64 1.91.1-1720564633 1.92.0-1722473020
2024-08-02 12:52:24 status half-configured code:amd64 1.91.1-1720564633
2024-08-02 12:52:24 status unpacked code:amd64 1.91.1-1720564633
2024-08-02 12:52:24 status half-installed code:amd64 1.91.1-1720564633
2024-08-02 12:52:24 status triggers-pending desktop-file-utils:amd64 0.27-1
2024-08-02 12:52:24 status triggers-pending gnome-menus:amd64 3.36.0-1.1
2024-08-02 12:52:24 status triggers-pending mailcap:all 3.70+nmu1
2024-08-02 12:52:26 status triggers-pending shared-mime-info:amd64 2.4-1
2024-08-02 12:52:28 status unpacked code:amd64 1.92.0-1722473020
2024-08-02 12:52:28 startup packages configure
2024-08-02 12:52:28 configure code:amd64 1.92.0-1722473020 <none>
2024-08-02 12:52:28 status unpacked code:amd64 1.92.0-1722473020
2024-08-02 12:52:28 status half-configured code:amd64 1.92.0-1722473020
2024-08-02 12:52:30 status installed code:amd64 1.92.0-1722473020
```

```
$ who -b
         system boot  2024-08-03 12:28
```

**Comment by andrewpollock** [comment]
Looking in Chrome's developer console, I see:

```
mainThreadExtensionService.ts:107 Activating extension 'vscodevim.vim' failed: Not Found.
$onExtensionActivationError	@	mainThreadExtensionService.ts:107
```
